### ISSUE TITLE
Question: The correct way to compile without main function

### ISSUE THREAD

**Issue by timonson** [WebAssembly/wasi-sdk#110]
Hi guys, I would like to create a WASM file from the following C file:

```c
int total_count = 0;

// Modules can have state
int count() {
  return ++total_count;
}

// They can do work
int add(int a, int b) {
  return a + b;
}

// But they only work with numbers
char * string() {
  return "Hello, world!";
}
```

Besides other things, I tried to run `$WASI_SDK_DIR/bin/clang --target=wasm32-unknown-wasi -Wl,--no-entry -nostartfiles --sysroot $WASI_SDK_DIR/share/wasi-sysroot -o module.wasm module.c`. This command creates a module.wasm file without compiler error but the file is almost empty unfortunately.
 
My goal is to create an equal file with wasi-sdk to what the following command does: `clang --target=wasm32 --no-standard-libraries -Wl,--export-all -Wl,--no-entry -o module.wasm module.c`

I don't need a `main` function because I want to import these functions as ES Modules later with the help from [deno](https://deno.land/std/manual.md#wasm-support).

What am I doing wrong?
Thank you!

**Comment by sbc100** [comment]
Currently WASI only supports programs with `main` functions.   See https://github.com/WebAssembly/WASI/issues/13 for the plan to extend this.

Having said that there are various ways to achieve what you want in a non-standards-conforming way today.  

I would still recommend keeping an empty main function around if only to ensure that all the correct startup functions are called.   For example the `_start` function that calls `main` is also in charge of calling things like C++ constructor (you can do this youself by calling `__wasm_call_ctors` if you prefer).

In terms of exporting functions probably the best way is to use the `__attribute__((export_name))` clang attribute to tag the functions you want to export and the name you want to export them under.
I would also have though the `--export` command line flag should work too. Is it not working for you?

**Comment by timonson** [comment]
Hi @sbc100  thank you a lot. I could make it work with the `--export-all` flag thanks to your advice.

**Comment by mmathys** [comment]
For anyone looking at this in the future, I made it work like this:

```c
int main(int argc, char **argv) { return 0; }

__attribute__((export_name("entry")))
int entry(int argc, char **argv) {
...
}
```

compile using
```bash
clang -Wl,--no-entry -o example.wasm example.c
```
using `clang` from the WASI-SDK.

**Comment by sbc100** [comment]
You shouldn't need to define a dummy main like that. I think the link flag you want is `-mexec-model=reactor`

**Comment by mmathys** [comment]
Thanks! Updated the example.
