### ISSUE TITLE
missing headers: netdb.h, pwd.h

### ISSUE THREAD

**Issue by jendrikw** [WebAssembly/wasi-sdk#112]

**Comment by jendrikw** [comment]
Duplicate of https://github.com/WebAssembly/wasi-libc/issues/47 and https://github.com/WebAssembly/wasi-libc/issues/18.

**Comment by zlonqi** [comment]
> Duplicate of [WebAssembly/wasi-libc#47](https://github.com/WebAssembly/wasi-libc/issues/47) and [WebAssembly/wasi-libc#18](https://github.com/WebAssembly/wasi-libc/issues/18).

Hi, I also found missing netdb.h in wasi-sdk. Could I trouble you to give some advices? Thank you very much.

**Comment by sunfishcode** [comment]
WASI does not yet support the functionality needed to implement netdb.h. Before wasi-sdk can support it, we'll need WASI proposals to support it.
