### ISSUE TITLE
wasi-sdk-9 requires libtinfo.so.5 

### ISSUE THREAD

**Issue by jedisct1** [WebAssembly/wasi-sdk#117]
On Linux, version 9 of `wasi-sdk` seems to have a new dependency:

```sh
$ clang
clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

The current Ubuntu only ships with `libtinfo.so.6`.

**Comment by jedisct1** [comment]
And Xenial is old enough to ship with `libtinfo.so.5` but `clang` isn't usable either:

```sh
clang: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by clang)
```

**Comment by jedisct1** [comment]
Unfortunately, we can't ship universal Linux binaries.

Maybe `wasi-sdk-9.0-linux.tar.gz` should be renamed to `wasi-sdk-9.0-ubuntu18.04.tar.gz` in order to clarify its requirements?

**Comment by pchickey** [comment]
I built the release on Ubuntu 18.04. I think the right thing to do is rename it for the moment. If we can make it compatible with more places by building it on 16.04, I will upload that one as well.

**Comment by sbc100** [comment]
Since we build using a docker image, switching should be trivial.  It looks like we currently build against `debian:stretch` (unless I'm misunderstanding @pchickey it should not be relevant which version of linux you were running if you used the `docker_build.sh` script).

Hopefully we can find a way to build a single release that works on all modern linux distros without having to create multiple archives.

Perhaps we can create add some minimal testing to the `docker_build.sh` script that verifies the executables can run on a reasonable set of modern distros.

**Comment by sbc100** [comment]
@jedisct1 when you say the current Ubuntu only ships `libtinfo.so.6` which version are you referring too specifically?

**Comment by jedisct1** [comment]
> when you say the current Ubuntu only ships libtinfo.so.6 which version are you referring too specifically?

Ubuntu Server 19.10

**Comment by pchickey** [comment]
I built it locally on my machine, not using the docker file, because I goofed. Will do a docker build now based on stretch, which should be more compatible.

**Comment by sbc100** [comment]
OK, lets see if that fixes the issue at hand.

I still think it might be nice to run basic tests on a handful of distros as part of `docker_build.sh`.   I'll open a bug for that.

**Comment by jendrikw** [comment]
Arch Linux also ships with `libtinfo.so.6`.

**Comment by sbc100** [comment]
It looks like when we build against our docker image there is no dependency on tinfo at all. 

```
$ ldd wasi-sdk-9.1g6cdd100d8753/bin/clang
	linux-vdso.so.1 (0x00007ffef133b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3c41410000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3c41405000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3c41400000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3c41227000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3c410e2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3c410c8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3c40f06000)
```

So hopefully this is issue will go away once #118 lands and we publish a new version

**Comment by pchickey** [comment]
I believe this is resolved with https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-10
