### ISSUE TITLE
Document linux requirements for prebuilt binaries

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wasi-sdk#118]
See https://github.com/WebAssembly/wasi-sdk/issues/117

Currently we build against `debian:stretch` inside a docker contains and hope for the best.  We should probably document the minimal requires for libc, libc++ and any other dynamic libraryies our binaries use.

We should perhaps also do some minimal testing against some reasonable subset of modern distros as part of the build/release process.

**Comment by sunfishcode** [comment]
I believe the libtinfo issue is fixed now, and in general, we build with a reasonable linux distro and haven't had any recent reports of this being a problem, so I don't think we need documentation at this time. If people do hit problems, please file new issues!
