### ISSUE TITLE
Pointer conversion between int and long.

### ISSUE THREAD

**Issue by jendrikw** [WebAssembly/wasi-sdk#121]
The wasi sdk currently implements https://github.com/WebAssembly/tool-conventions/blob/master/BasicCABI.md, so `int` and `long` are both 32 bits wide.

When mixing int and long, like in `int l2 = 1L;`, there is no warning.

But when using pointers, a warning is issued:

```c
int *i = NULL;
long *l = i;
```

`warning: incompatible pointer types initializing 'long *' with an expression of type 'int *' [-Wincompatible-pointer-types]`.

I find this especially confusing, because neither `int32_t` nor `int64_t` can be used if a long pointer is required in a library function.

Why is there this discrepencay between normal integers and pointers?

**Comment by sbc100** [comment]
This appears no different how clang and gcc behave on x86.

Your first example produces no error with `clang -m32` or `gcc -m32` and your second example produces `incompatible pointer type` error with both. 

wasm32 is an IPL32 platform just like x86 so I t think that this is correct and to be expected.

For the precise reason that `int l2 = 1L;` does not generate an error you'd have to dig deep into C/C++ type coercion rules (maybe https://en.cppreference.com/w/cpp/language/implicit_conversion).   Note that `int l2 = 1LL;` also works (at least in gcc and clang on my system) and does not produce any warning (even with `-Wall -pedantic`)

**Comment by jendrikw** [comment]
I asked about this on stackoverflow. The reason for the warning is that int and long are treated as different types even if they are the same size. Here's the answer for reference: https://stackoverflow.com/questions/61128589/incompatible-pointer-when-int-and-long-are-the-same/61128923.
