### ISSUE TITLE
Some quick questions for the flag of compiling C++ code

### ISSUE THREAD

**Issue by leonwanghui** [WebAssembly/wasi-sdk#131]
Sorry to interrupt, but I found that C++ can only support be compiled with `-fno-exceptions` flag, so my question is if it can also support `-fno-rtti` flag, and what impact it would cause if I enable this flag when compiling C++ code with clang++ compiler? Thanks!

**Comment by sunfishcode** [comment]
Yes, wasi-sdk supports `-fno-rtti`. That flag typically reduces the code size of C++ applications, by avoiding the extra type metadata and strings.

**Comment by leonwanghui** [comment]
@sunfishcode Thanks for the quick answers, if I enable `-fno-rtti`, would it have some impact on wasm binary file, for example reducing wasm binary file size, or removing some type metadata in wasm IR? Please correct me if I have some misunderstanding, thanks~

**Comment by sunfishcode** [comment]
Yes, it typically reduces the size of wasm binaries.

**Comment by leonwanghui** [comment]
Thanks!
