### ISSUE TITLE
wasi-sdk-11 release: 18.04 deb missing?

### ISSUE THREAD

**Issue by orestisfl** [WebAssembly/wasi-sdk#142]
I don't see a 18.04 deb in https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-11. Is 16.04 mislabeled?

**Comment by pchickey** [comment]
Sounds good to me. I am hesitant to rename the files currently in the release because I (and maybe others?) already download them in CI scripts. We could instead re-upload the 16.04 one with the suffix dropped, and stick to that process in the future.
