### ISSUE TITLE
Loading wasm built with C++ fails: missing fd_close and fd_seek

### ISSUE THREAD

**Issue by ivannp** [WebAssembly/wasi-sdk#145]
A simple wasm module loads when build with C, malloc and free, but fails to load when build with C++, new and delete. The runtime error from wasmer is:

Error: `3 link errors: (1 of 3) Import not found, namespace: wasi_snapshot_preview1, name: fd_close (2 of 3) Import not found, namespace: wasi_snapshot_preview1, name: fd_seek (3 of 3) Import not found, namespace: wasi_snapshot_preview1, name: fd_write`

**Comment by sbc100** [comment]
What wasi runtime are you trying to run the binary under? 

It looks like the runtime is missing `fd_seek` and `fd_write` syscalls.

**Comment by ivannp** [comment]
wasmer. Opened an issue there. Thanks!

**Comment by KestutisMa** [comment]
Same issue. I opened stackoverflow question: https://stackoverflow.com/questions/62680774/webassembly-instantiate-fails-when-wasm-file-was-compiled-with-clang-but-wo
Any progress?

**Comment by ivannp** [comment]
After the above advise, I opened [an issues against wasmer](https://github.com/wasmerio/wasmer/issues/1471). The solution proposed there worked for me.

The following changes made my code work on wasmer:

```
// Compile the module
wasmer_module_t *module = nullptr;
wasmer_result_t res = wasmer_compile(&module, bytes, len);
if (res != wasmer_result_t::WASMER_OK)
{
    return 0;
}

// Get the WASI version
Version version = wasmer_wasi_get_version(module);

wasmer_import_object_t *importObj = wasmer_wasi_generate_import_object_for_version(
    static_cast<unsigned char>(version),
    nullptr,
    0,
    nullptr,
    0,
    nullptr,
    0,
    nullptr,
    0);

wasmer_instance_t *instance = NULL;
res = wasmer_module_import_instantiate(&instance, module, importObj);
```

**Comment by sbc100** [comment]
I don't think this is an issue with the wasi-sdk is it?  can we close this issue?

**Comment by sunfishcode** [comment]
This appears to be resolved; feel free to re-open if there's any followup!
