### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by pchickey** [WebAssembly/wasi-sdk#147]
The WASI subgroup is changing the default branch names in all repositories to `main`.

Please consider this a tracking issue. It is not intended for public debate.

* [x] Change branch name
* [ ] Update CI
* [ ] Update build scripts
* [ ] Update documentation

**Comment by sunfishcode** [comment]
As an update, this is now waiting for Github to add functionality to make it seamless to rename branches. See https://github.com/WebAssembly/WASI/issues/290 for discussion.

**Comment by pchickey** [comment]
The default branch has been renamed!
`master` is now named `main`

If you have a local clone, you can update it by running:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
