### ISSUE TITLE
Windows builds require libcc_s_seh-1.dll to be available

### ISSUE THREAD

**Issue by vvuk** [WebAssembly/wasi-sdk#148]
The Windows Clang builds require `libcc_s_seh-1.dll`, which is present in the Git Bash environment (mingw based).  This is unexpected; I'm not sure why this dependency is coming in to clang itself.  We should fix this, as right now the generated wasi SDK for Windows only works if you have this DLL in your path from somewhere.

(I can take a look at some point, but if someone beats me to it please do)

**Comment by sbc100** [comment]
Any idea on how to fix this welcome.  The core devs working on wasi-sdk don't use windows themseleves so its really up to windows users and contributors to keep this working.

**Comment by vvuk** [comment]
The issue is this:

```
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/ProgramData/chocolatey/bin/gcc.exe
...
-- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe - skipped
```

Basically the image environment has some random gcc in it, and cmake picks this up by default.  I believe the actions windows image should have VS in it which is what we want to use.  Will try to wrangle the cmake setup.

**Comment by ringoz** [comment]
the problem resurfaced in recent v23 release, probably after #429

**Comment by alexcrichton** [comment]
Thanks for the report! I've opened https://github.com/WebAssembly/wasi-sdk/issues/454 to track that, and I'll work on investigating it over there.
