### ISSUE TITLE
What does the file predefined-macros.txt mean?

### ISSUE THREAD

**Issue by Weining2019** [WebAssembly/wasi-sdk#149]
Hi,

I noticed that there is a file named share/wasi-sysroot/share/wasm32-wasi/predefined-macros.txt. What does it mean and how to use it when compiling an application? Should I pass it to clang explicitly?

Thanks

**Comment by sunfishcode** [comment]
It's just informative. You don't need to do anything with it.

It's a report of the macros that clang predefines as well as the macros defined by libc headers. It's of interest to clang and WASI libc developers, and not something that users need to do anything with. In fact, we probably should exclude that file, and the others next to it, from the installation.

**Comment by Weining2019** [comment]
Thanks for the explanation.
