### ISSUE TITLE
LLVM 11?

### ISSUE THREAD

**Issue by zeux** [WebAssembly/wasi-sdk#154]
Are there plans to release an LLVM 11 build of WASI SDK?

The reason I ask is that SIMD support is unfortunately not very usable in LLVM 10 that's currently bundled, due to the absence of the intrinsics header (that was migrated from Emscripten to LLVM in the 11 timeline) and various instructions that were standardized a bit later missing + suboptimal codegen around some parts of SIMD.

**Comment by sunfishcode** [comment]
We usually wait for official LLVM releases, and it looks like LLVM 11 hasn't quite happened yet. The llvm.org home page says "~~Aug 26~~Soon: 11.0.0-final". It looks like they're on `-rc5` now, so my inclination here is to wait for the release, which will hopefully be soon.

**Comment by zeux** [comment]
Ah, the fact that Emscripten uses clang 12 led me to believe that clang 11 has been released. I agree it would make sense to wait for the official release.

**Comment by sunfishcode** [comment]
LLVM 11.0 is now released; #158 is a PR to update wasi-sdk.

**Comment by sunfishcode** [comment]
We've now tagged a release with LLVM 11: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-12
