### ISSUE TITLE
Does it support LLVM8 anymore?

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/wasi-sdk#155]
Sorry, does the "wasi-sdk" still support LLVM8? If it's not, I think it's better to update the README correspondingly. 

> Upstream Clang and LLVM (from 8.0 onwards) can compile for WASI out of the box, and WebAssembly support is included in them by default. So, all that's done here is to provide builds configured to set the default target and sysroot for convenience.

**Comment by sunfishcode** [comment]
Indeed, support for LLVM 8.0 was recently dropped. I've now submitted #156 to update the README.
