### ISSUE TITLE
-msimd128 seems not work on wasi-sdk-11

### ISSUE THREAD

**Issue by sophy228** [WebAssembly/wasi-sdk#160]
I used below C code simd.c:
`#include <stdio.h>
void multiply_arrays(int* out, int* in_a, int* in_b, int size) {
  for (int i = 0; i < size; i++) {
    out[i] = in_a[i] * in_b[i];
  }
}

int main(int argc, char * argv[])
{
    int out[10];
    int in_a[10];
    int in_b[10];

    multiply_arrays(out, in_a, in_b, 10);

    for (int i = 0; i < 10; i++) {
        printf("%d ", out[i]);
    }
    printf("\n");
}`

and compile with:
/opt/wasi-sdk/bin/clang --sysroot=/opt/wasi-sdk/share/wasi-sysroot -O0 -msimd128 -o simd.wasm simd.c

But the actual multiply_arrays is like this:

`(func $multiply_arrays (type 8) (param i32 i32 i32 i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)
    global.get 0
    local.set 4
    i32.const 32
    local.set 5
    local.get 4
    local.get 5
    i32.sub
    local.set 6
    i32.const 0
    local.set 7
    local.get 6
    local.get 0
    i32.store offset=28
    local.get 6
    local.get 1
    i32.store offset=24
    local.get 6
    local.get 2
    i32.store offset=20
    local.get 6
    local.get 3
    i32.store offset=16
    local.get 6
    local.get 7
    i32.store offset=12
    block  ;; label = @1
      loop  ;; label = @2
        local.get 6
        i32.load offset=12
        local.set 8
        local.get 6
        i32.load offset=16
        local.set 9
        local.get 8
        local.set 10
        local.get 9
        local.set 11
        local.get 10
        local.get 11
        i32.lt_s
        local.set 12
        i32.const 1
        local.set 13
        local.get 12
        local.get 13
        i32.and
        local.set 14
        local.get 14
        i32.eqz
        br_if 1 (;@1;)
        local.get 6
        i32.load offset=24
        local.set 15
        local.get 6
        i32.load offset=12
        local.set 16
        i32.const 2
        local.set 17
        local.get 16
        local.get 17
        i32.shl
        local.set 18
        local.get 15
        local.get 18
        i32.add
        local.set 19
        local.get 19
        i32.load
        local.set 20
        local.get 6
        i32.load offset=20
        local.set 21
        local.get 6
        i32.load offset=12
        local.set 22
        i32.const 2
        local.set 23
        local.get 22
        local.get 23
        i32.shl
        local.set 24
        local.get 21
        local.get 24
        i32.add
        local.set 25
        local.get 25
        i32.load
        local.set 26
        local.get 20
        local.get 26
        i32.mul
        local.set 27
        local.get 6
        i32.load offset=28
        local.set 28
        local.get 6
        i32.load offset=12
        local.set 29
        i32.const 2
        local.set 30
        local.get 29
        local.get 30
        i32.shl
        local.set 31
        local.get 28
        local.get 31
        i32.add
        local.set 32
        local.get 32
        local.get 27
        i32.store
        local.get 6
        i32.load offset=12
        local.set 33
        i32.const 1
        local.set 34
        local.get 33
        local.get 34
        i32.add
        local.set 35
        local.get 6
        local.get 35
        i32.store offset=12
        br 0 (;@2;)
      end
    end
    return)`

What I want is some like:
`(loop
  (v128.store align=4
    … get address in `out` …
    (i32x4.mul
       (v128.load align=4 … get address in `in_a` …)
       (v128.load align=4 … get address in `in_b` …)
    …
  )
)`

**Comment by sbc100** [comment]
@tlively ?

Most likely this is because wasi-sdk-11 is based on a fairly old version of llvm (llvm 10 I think).    Support for llvm 11 was just landed so you might want to try using one of the reset CI artifacts which will contains the llvm 11 version of the sdk.

**Comment by sophy228** [comment]
@sbc100  still not work with sdk here

 https://github.com/WebAssembly/wasi-sdk/pull/158/checks?check_run_id=1242716713

**Comment by sunfishcode** [comment]
Can you try with `-O2` rather than `-O0`? The `-O0` disables LLVM's optimizer, including loop auto-vectorization.

**Comment by sophy228** [comment]
@sunfishcode  Yes I tried the O2 and O3 , but the multiply_arrays will be optimized inline into main, and final wasm is ：


(func $main (type 3) (param i32 i32) (result i32)
    (local i32)
    global.get 0
    i32.const 160
    i32.sub
    local.tee 2
    global.set 0
    i32.const 1024
    local.get 2
    i32.const 144
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 128
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 112
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 96
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 80
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 64
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 48
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 32
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    i32.const 16
    i32.add
    call $printf
    drop
    i32.const 1024
    local.get 2
    call $printf
    drop
    i32.const 10
    call $putchar
    drop
    local.get 2
    i32.const 160
    i32.add
    global.set 0
    i32.const 0)

**Comment by sophy228** [comment]
export the multiply_arrays :

/mnt/d/repos/dist-ubuntu-xenial/wasi-sdk-11.5gaea2680940cb/bin/clang --sysroot=/mnt/d/repos/dist-ubuntu-xenial/wasi-sysroot -g -O3 -msimd128  -Wl,--export=multiply_arrays -o simd.wasm simd.c

  
(func $multiply_arrays (type 8) (param i32 i32 i32 i32)
    (local i32 i32 i32 i32 i32)
    block  ;; label = @1
      local.get 3
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      i32.const 0
      local.set 4
      block  ;; label = @2
        local.get 3
        i32.const 3
        i32.le_u
        br_if 0 (;@2;)
        local.get 1
        local.get 3
        i32.const 2
        i32.shl
        local.tee 5
        i32.add
        local.get 0
        i32.gt_u
        local.get 0
        local.get 5
        i32.add
        local.tee 6
        local.get 1
        i32.gt_u
        i32.and
        br_if 0 (;@2;)
        local.get 2
        local.get 5
        i32.add
        local.get 0
        i32.gt_u
        local.get 6
        local.get 2
        i32.gt_u
        i32.and
        br_if 0 (;@2;)
        local.get 3
        i32.const -4
        i32.and
        local.tee 4
        local.set 7
        local.get 0
        local.set 5
        local.get 2
        local.set 6
        local.get 1
        local.set 8
        loop  ;; label = @3
          local.get 5
          local.get 6
          v128.load align=4
          local.get 8
          v128.load align=4
          i32x4.mul
          v128.store align=4
          local.get 5
          i32.const 16
          i32.add
          local.set 5
          local.get 6
          i32.const 16
          i32.add
          local.set 6
          local.get 8
          i32.const 16
          i32.add
          local.set 8
          local.get 7
          i32.const -4
          i32.add
          local.tee 7
          br_if 0 (;@3;)
        end
        local.get 4
        local.get 3
        i32.eq
        br_if 1 (;@1;)
      end
      local.get 3
      local.get 4
      i32.sub
      local.set 7
      local.get 1
      local.get 4
      i32.const 2
      i32.shl
      local.tee 8
      i32.add
      local.set 5
      local.get 2
      local.get 8
      i32.add
      local.set 6
      local.get 0
      local.get 8
      i32.add
      local.set 8
      loop  ;; label = @2
        local.get 8
        local.get 6
        i32.load
        local.get 5
        i32.load
        i32.mul
        i32.store
        local.get 5
        i32.const 4
        i32.add
        local.set 5
        local.get 6
        i32.const 4
        i32.add
        local.set 6
        local.get 8
        i32.const 4
        i32.add
        local.set 8
        local.get 7
        i32.const -1
        i32.add
        local.tee 7
        br_if 0 (;@2;)
      end
    end)
