### ISSUE TITLE
wasm32-wasi-clang compilation failed 

### ISSUE THREAD

**Issue by ZW007** [WebAssembly/wasi-sdk#165]
Hi! (1) I wonder the difference between wasi-libc and wasm32-wasi-clang?  

can i always use wasm32-wasi-clang

(2) Previously, I just used wasm32-wasi-clang for compiling .c file to wasm and it worked fine, until I tried to compile this:
**wasm32-wasi-clang -I ./ lenet.c main.c -lm -v -o mainWasi.wasm**

clang -cc1 version 10.0.0 based upon LLVM 10.0.0 default target wasm32-wasi
ignoring nonexistent directory "/opt/wasi-sysroot/include/wasm32-wasi"
#include "..." search starts here:
#include <...> search starts here:
 .
 /opt/wasi-sdk/lib/clang/10.0.0/include
 /opt/wasi-sysroot/include
End of search list.
 "/opt/wasi-sdk/bin/wasm-ld" -L/opt/wasi-sysroot/lib/wasm32-wasi /opt/wasi-sysroot/lib/wasm32-wasi/crt1.o /tmp/lenet-302c6c.o /tmp/main-ab249b.o -lm -lc /opt/wasi-sdk/lib/clang/10.0.0/lib/wasi/libclang_rt.builtins-wasm32.a -o mainWasi.wasm
wasm-ld: error: /tmp/main-ab249b.o: undefined symbol: system
wasm-ld: error: /tmp/main-ab249b.o: undefined symbol: system
wasm-ld: error: /tmp/main-ab249b.o: undefined symbol: system
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sunfishcode** [comment]
wasi-libc is packaged as part of wasi-sdk. If I understand correctly, wasm32-wasi-clang is the clang from wasi-sdk.

`system` isn't currently supported on wasi-libc/wasi-sdk. Could you describe what you're using `system` for? It's possible there are alternative approaches we can help with.

**Comment by ZW007** [comment]
@sunfishcode 

> wasi-libc is packaged as part of wasi-sdk. If I understand correctly, wasm32-wasi-clang is the clang from wasi-sdk.

I found wasm32-wasi-clang  from lucet https://bytecodealliance.github.io/lucet/Compiling-on-Linux.html
After i  followed the instruction above, wasm32-wasi-clang just works out of the box. Do i need to do more to make clang wasm work?

> system isn't currently supported on wasi-libc/wasi-sdk. Could you describe what you're using system for? It's possible there are alternative approaches we can help with.

I do not understand why do you mean by system ( 

I just wanted to compile a simple dnn task.  https://github.com/ZW007/lenet5

So i did wasm32-wasi-clang -I ./ lenet.c main.c -lm -v -o mainWasi.wasm

**Comment by sunfishcode** [comment]
The wasm32-wasi-clang should work without any additional setup, if you have it installed from lucet or wasi-sdk.

The `lenet5` code linked above calls a function named `system` in a few places: https://github.com/ZW007/lenet5/blob/main/main.c#L85. WASI doesn't support that function. Fortunately, it's only used in a few inessential places, and it looks like you could replace the first two `system` calls with `exit(1)` and the last with `exit(0)`.

**Comment by ZW007** [comment]
@sunfishcode Thank you! Yes, remove the system() just works! But when gcc compile it to elf and run it. there is no problem, but use wasm32-wasi-clang -I ./ lenet.c main.c -lm  -o mainWasi.wasm  There is no compilation error, but I cannot open the file 
https://github.com/ZW007/lenet5/blob/main/main.c#L82

**Comment by ZW007** [comment]
How can get more memory for wasmtime ;(
