### ISSUE TITLE
Makefile: Anything actually UNIX specific?

### ISSUE THREAD

**Issue by IngwiePhoenix** [WebAssembly/wasi-sdk#168]
Hello there!

I am experimenting with WASM via Emscripten and Wasm3 - but I want to go a little further and take the WASI route to learn more about the possibilities that get with WASM.

So I took a look at the makefile. A lot of CMake-ing and basic shell ops.

Is there anything that I may not be spotting that is specifically UNIX only? I use "UNIX" as an opaque term here, since it was mentioned that environments like git-bash do work with this - and, well, for the lack of a better description ;)

If this is not the case, it'd be quite easily possible to automate the build on plain Windows by utilizing Chocolatey - there are packages for Ninja, CMake and Make. Even VS2019 can be installed that way. i.e.: `choco install cmake ninja make visualstudio2019community visualstudio2019community-buildtools`

Then you'd only have to change `cp` and `mv` to Windows compatible variants and could just `make` in the root.

Before I go and try to port the makefile myself, I just want to be sure that I am not overlooking anything before running straight into a wall, you see. :) 

Kind regards,
Ingwie

**Comment by sunfishcode** [comment]
Welcome! The wasi-libc Makefile uses some tools like sed, find, and diff, though those parts are effectively just doing consistency checking, which could be disabled without affecting the main product of the build.

**Comment by sbc100** [comment]
Also, if just want to experiment with SDK you can download the existing mingw SDK from the releases page: https://github.com/WebAssembly/wasi-sdk/releases.

**Comment by abrown** [comment]
The original question is answered; thanks!
