### ISSUE TITLE
Couldn't compile C code: pthread.h not found, need to enable minimal signal emulation

### ISSUE THREAD

**Issue by elimisteve** [WebAssembly/wasi-sdk#174]
Using wasi-sdk-12 on Linux:

```
$ clang cp-skip-unused.c -o demo.wasm
In file included from cp-skip-unused.c:171:
/opt/wasi-sdk/share/wasi-sysroot/include/signal.h:2:2: error: "wasm lacks signal support; to enable minimal signal emulation, compile with -D_WASI_EMULATED_SIGNAL and link with -lwasi-emulated-signal"
#error "wasm lacks signal support; to enable minimal signal emulation, \
 ^
cp-skip-unused.c:351:11: fatal error: 'pthread.h' file not found
        #include <pthread.h>
                 ^~~~~~~~~~~
2 errors generated.
```

How do I do this? I'm not sure what needs to be recompiled nor which compiler I needed to pass those flags to.

Thanks!

**Comment by pchickey** [comment]
If you want to use the minimal signal emulation, you'd invoke your clang like:
```
$ clang -D_WASI_EMULATED_SIGNAL -Wl,wasi-emulated-signal cp-skip-unused.c -o demo.wasm
```
Even with that minimal signal emulation, pthread.h won't be found. Wasm does not yet support threads so WASI does not support them, see also https://github.com/WebAssembly/WASI/issues/296 https://github.com/WebAssembly/wasi-sdk/issues/22

**Comment by abrown** [comment]
This should no longer be an issue: use the `wasm32-wasi-threads` target that has been worked on in many PRs by various people over the last few months. A pre-release for this functionality is available in the [`wasi-sdk-20+threads`](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-20%2Bthreads) artifacts. (More instructions for how to use this new target are available [here](https://bytecodealliance.org/articles/wasi-threads)).
