### ISSUE TITLE
Publish an official Docker image

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wasi-sdk#176]
It would be nice to have an official wasi-sdk Docker image for use in CI; the [current images I see on Docker Hub are unofficial](https://hub.docker.com/search?q=wasi-sdk&type=image).

**Comment by abrown** [comment]
See https://github.com/bytecodealliance/sightglass/pull/104 for alternatives to this (e.g. multi-stage builds).

**Comment by pchickey** [comment]
The official docker image could be as simple as an ubuntu base and installing the deb, right?

**Comment by abrown** [comment]
Yeah, exactly. And maybe setting some environment variables. Possibly:
```
FROM ubuntu:18.04
WORKDIR /
RUN apt update && apt install -y wget
RUN wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
RUN tar xvf wasi-sdk-12.0-linux.tar.gz
ENV CC=/wasi-sdk-12.0/bin/clang
ENV CXX=/wasi-sdk-12.0/bin/clang++
ENV LD=/wasi-sdk-12.0/bin/lld
ENV CFLAGS=--sysroot=/wasi-sdk-12.0/share/wasi-sysroot
ENV CXXFLAGS=--sysroot=/wasi-sdk-12.0/share/wasi-sysroot
ENV PATH /wasi-sdk-12.0
```

**Comment by abrown** [comment]
I think we would want to wire it up with the CI somehow so that, upon release, some `docker push ...` command is run.

**Comment by pchickey** [comment]
Currently CI doesn't do any publishing of artifacts, it just create some tarballs that the person on release duties (typically me?) downloads locally and uploads to the github release page. This is mostly out of laziness - I havent had time to do the programming in yaml or however you do these things in github CI/Actions, and figuring out how credentials are managed.

First step would be to add that Dockerfile and a shell script containing the commands to build and `docker push ...` in the tarball. But if you'd like to volunteer for automating publishing of any of the artifacts, it would save some toil!

**Comment by abrown** [comment]
Ok, I think I understand [from the docs](https://docs.github.com/en/actions/guides/publishing-docker-images) how to do this and am trying to figure out if the owner of [the webassembly name on DockerHub](https://hub.docker.com/u/webassembly) will share it with this project so we can publish it to `webassembly/wasi-sdk` (which sounds official). We'll need credentials to publish with, though: any thoughts on who should own those?

**Comment by thewtex** [comment]
In case it is useful, we have a [`dockcross`](https://github.com/dockcross/dockcross) `web-wasi` image. This has `CC, `CXX`, etc. set, but also enables source code and build artifacts outside of the image, CMake cross-compilation toolchain setup, and more.
