### ISSUE TITLE
ICU support

### ISSUE THREAD

**Issue by dbezhetskov** [WebAssembly/wasi-sdk#180]
Hi, right now wasm-sdk isn't strong enough to support ICU libs and some needs to create workarounds for that, for example https://bugzilla.mozilla.org/show_bug.cgi?id=1706949.

But iiuc wasi with atomic and threads support will support ICU libs eventually, right?

**Comment by wingo** [comment]
Just to see if I understand the issue here @dbezhetskov -- right now, you can't compile the ICU libraries for the WASI target because they assume the presence of `<atomic>` and `<thread>`, right?  And I guess the question is, is it the plan of WASI SDK to add support for `<atomic>` / `<thread>` even in a no-threads configuration, or do we need to get a WASI patch upstream in ICU?

**Comment by sbc100** [comment]
For more info on the current status of thread support see https://github.com/WebAssembly/wasi-libc/issues/209.   (In fact, this issue should probably be moved to wasi-libc).

I think we probably should include a version of wasi-libc that has null <atomic> and <thread>.  That would allow code that expects threading and atomics at compile time to be built (even though new thread creation would then fail at runtime).     I imagine code such as ICU works find in single threaded mode too.   However, I would also considering filing a bug upstream in ICU suggesting they add a configuration option such as HAS_THREADS that could be disabled on platforms such as WASI.

**Comment by dbezhetskov** [comment]
Thanks @wingo for the clarification, right, we don't need to patch ICU sources, we just need `<atomic>` and `<thread>`.
In my opinion it is better to add no-op/stub implementation of threads and atomics in WASI repo rather than adding HAS_THREADS support in ICU because right now only WASI requires no-thread build.

@sbc100
Just for your information, we already have some noop workaround for threads in mozilla for wasi https://phabricator.services.mozilla.com/D110073.

**Comment by abrown** [comment]
The situation has changed since this issue was posted: now, if you want atomics support you can use the `wasm32-wasi-threads` target. Also, if only stubbed-out support is needed, take a look at: #22.
