### ISSUE TITLE
wasm-ld issue with "multi3.c.obj"

### ISSUE THREAD

**Issue by mrrostam** [WebAssembly/wasi-sdk#187]
Hi folks,

I am trying to compile [cJSON](https://github.com/DaveGamble/cJSON) with the following command (FYI everything was working fine before adding `cJSON.c` to the build command)

```console
clang --target=wasm32-wasi --sysroot ./sysroot -nostartfiles -O2 -flto -Wl,--no-entry -Wl,--export-all -Wl,--lto-O2 -Wl,--allow-undefined -Wl,--import-memory main.c cJSON.c -v -o main.wasm
```

However, it seems that `wasm-ld` has a weird problem with it for some reasons and complains:

```console
wasm-ld: error: multi3.c.obj: Bad relocation type: 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any help would be much appreciated

**Comment by sbc100** [comment]
Seems like perhaps a mismatch between the version of the compiler you are using and the version that was used to build the sysroot.

Which version of `clang` are you using?   (what does `which clang` and/or `clang -v` say?).

**Comment by mrrostam** [comment]
```console
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by mrrostam** [comment]
ok, I've gone the old [libclang_rt.builtins-wasm32-wasi-11.0.tar.gz](https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-11/libclang_rt.builtins-wasm32-wasi-11.0.tar.gz) instead of version 12 and that solved the problem.

Thank you so much for your help

**Comment by sbc100** [comment]
Unless you have good reason not to, you probably want to use the clang that comes with wasi-sdk, not the clang you have install in `/usr/bin`.
