### ISSUE TITLE
Any plan to support LLVM 13.x?

### ISSUE THREAD

**Issue by lum1n0us** [WebAssembly/wasi-sdk#191]
[WAMR](https://github.com/bytecodealliance/wasm-micro-runtime) hopes a WASI-SDK including *LLVM 13.x* in order to support [latest SIMD proposal](https://github.com/WebAssembly/simd/tree/main/proposals/simd), which has a lot of modified/new opcodes.

**Comment by sbc100** [comment]
In that past we have waited until a given llvm version is released before switch over (See  #178 and #108).   But we could at least upload a PR (and perhaps even a branch) that uses the the latest RC (llvmorg-13.0.0-rc3) to make sure it work and let folks try it out.

**Comment by sbc100** [comment]
Actually @sunfishcode has a PR that updates LLVM to something even less stable: #188.  That sounds like it will do that trick for you.

**Comment by sbc100** [comment]
According to llvm.org llvm 13 will be released in just 1 week on September 21st so it might be good to land a change that updates to that release and cut a wask-sdk release based on that, before we land #188.

**Comment by lum1n0us** [comment]
Thanks a lot. It is good news for us.
