### ISSUE TITLE
llvm missing

### ISSUE THREAD

**Issue by patrup** [WebAssembly/wasi-sdk#194]
Hello,
I am getting an error message on clone: 

From https://github.com/llvm/llvm-project
   5c52753d9ff2..7b424b933355  main       -> origin/main
fatal: remote error: upload-pack: not our ref bb31aec2cc85b6e2e85e687d086f85408b166c42
Fetched in submodule path 'src/llvm-project', but it did not contain bb31aec2cc85b6e2e85e687d086f85408b166c42. Direct fetching of that commit failed.

**Comment by sbc100** [comment]
Do you know where bb31aec2cc85b6e2e85e687d086f85408b166c42 is coming from?

It doesn't look like the src/llvm-project directory was ever pinned to that revision.  The following command shows nothing:

```
$ git log -p src/llvm-project/ | grep bb31aec2cc85b6e2e85e687d086f85408b166c42
```

The current revision we are pinned to is `d28af7c654d8db0b68c175db5ce212d74fb5e9bc` and that hasn't changed in many months (not since #178).

**Comment by patrup** [comment]
Hello,
thanks for the swift response. I just did a  
git clone --recurse-submodules https://github.com/llvm/llvm-project.git
and that was an error message I got.

**Comment by sbc100** [comment]
I'm a little confused, why are you trying to close `llvm-project.git` and not `wask-sdk.git`?

BTW that command (`git clone --recurse-submodules https://github.com/llvm/llvm-project.git`) should also work just fine, bit it only clones llvm, not wasi-sdk.

**Comment by patrup** [comment]
Sorry I copied that from the command line. I initially tried git clone —recourse-sub modules https://github.com/Holzschuh/wasi-sdk.git, which gave me the error message. Subsequently I tried to clone llvm directly with the previous command

**Comment by sbc100** [comment]
Can you try again with `wasi-sdk.git` and post the full command and the full output.  I don't see where `bb31aec2cc85b6e2e85e687d086f85408b166c42` could be coming from.  That is not a valid revision in either wasi-sdk or llvm-project.

**Comment by patrup** [comment]
❯ git clone --recurse-submodules https://github.com/holzschu/wasi-sdk.git
Cloning into 'wasi-sdk'...
remote: Enumerating objects: 618, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 618 (delta 101), reused 95 (delta 95), pack-reused 508
Receiving objects: 100% (618/618), 126.75 KiB | 2.18 MiB/s, done.
Resolving deltas: 100% (312/312), done.
Submodule 'src/config' (https://git.savannah.gnu.org/git/config.git) registered for path 'src/config'
Submodule 'src/llvm-project' (https://github.com/llvm/llvm-project) registered for path 'src/llvm-project'
Submodule 'src/wasi-libc' (https://github.com/holzschu/wasi-libc) registered for path 'src/wasi-libc'
Cloning into '/Users/patrickrupprecht/work/test/wasi-sdk/src/config'...
remote: Counting objects: 5325, done.
remote: Compressing objects: 100% (2243/2243), done.
remote: Total 5325 (delta 3040), reused 5325 (delta 3040)
Receiving objects: 100% (5325/5325), 1.21 MiB | 1.77 MiB/s, done.
Resolving deltas: 100% (3040/3040), done.
Cloning into '/Users/patrickrupprecht/work/test/wasi-sdk/src/llvm-project'...
remote: Enumerating objects: 4517235, done.
remote: Counting objects: 100% (922/922), done.
remote: Compressing objects: 100% (340/340), done.
remote: Total 4517235 (delta 606), reused 785 (delta 580), pack-reused 4516313
Receiving objects: 100% (4517235/4517235), 1.69 GiB | 6.19 MiB/s, done.
Resolving deltas: 100% (3599842/3599842), done.
Cloning into '/Users/patrickrupprecht/work/test/wasi-sdk/src/wasi-libc'...
remote: Enumerating objects: 9524, done.
remote: Counting objects: 100% (172/172), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 9524 (delta 87), reused 118 (delta 69), pack-reused 9352
Receiving objects: 100% (9524/9524), 2.77 MiB | 5.79 MiB/s, done.
Resolving deltas: 100% (4820/4820), done.
Submodule path 'src/config': checked out 'c8ddc8472f8efcadafc1ef53ca1d863415fddd5f'
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 13 (delta 11), reused 13 (delta 11), pack-reused 0
Unpacking objects: 100% (13/13), 1.95 KiB | 36.00 KiB/s, done.
From https://github.com/llvm/llvm-project
   ea56dcb73012..9b10e2b1cf01  main       -> origin/main
fatal: remote error: upload-pack: not our ref bb31aec2cc85b6e2e85e687d086f85408b166c42
Fetched in submodule path 'src/llvm-project', but it did not contain bb31aec2cc85b6e2e85e687d086f85408b166c42. Direct fetching of that commit failed.

**Comment by sbc100** [comment]
The problem is that your fork of `src/llvm-project/` points to an non-existent revision.     It looks like you changed it here:  https://github.com/holzschu/wasi-sdk/commit/28eeff7e2cae4f7b56e1c3b23e15e03ebc7beff3

It would have been useful if you could have mentioned from the beginning that it was your own fork that you were cloning and included the full command and output in the original report.

**Comment by patrup** [comment]
I had cloned the repo previously but I am not sure how the change got in there

**Comment by patrup** [comment]
my sincere apologies. Today is not my day. I did not notice that I landed in the WebAssembly Github Repo. I was under the impression it is the repo I cloned from.
