### ISSUE TITLE
Upgrade Clang in order to allow using the -shared option

### ISSUE THREAD

**Issue by Keithcat1** [WebAssembly/wasi-sdk#199]
Hi,
I would like to build WASM modules that are loadable with the Wasmtime runtime, but this seems to require the -shared option and I ran into a couple errors while using that:

C:\py>
C:\py>C:\wasi-sdk\bin\clang -shared add.c
clang: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(__main_argc_argv.o): undefined symbol: main
clang: error: linker command failed with exit code 1 (use -v to see invocation)

C:\py>C:\wasi-sdk\bin\clang -Wl,--shared add.c
wasm-ld: warning: creating shared libraries, with -shared, is not yet stable
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(sbrk.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol errno; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol __heap_base; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol mparams; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol mparams; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol mparams; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol mparams; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol mparams; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol __heap_base; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol __heap_base; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol _gm_; recompile with -fPIC
wasm-ld: error: c:/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi\libc.a(dlmalloc.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol __heap_base; recompile with -fPIC
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

C:\py>

clang version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: C:\wasi-sdk\bin

I wasn't able to use Emscripten because it seems to be generating WASM for the web but not for Wasmtime.

**Comment by Keithcat1** [comment]
Ok, how do I export symbols so that Wasmtime can find and call them? Simply compiling a .C file with some functions in it does not expose them.

**Comment by sbc100** [comment]
I believe you can either add `__attribute__((export_name("foo")))` to the functions you want to export or build with `-Wl,--export=foo`

**Comment by abrown** [comment]
@Keithcat1, you may be interested in https://github.com/WebAssembly/wasi-sdk/pull/338? Let's close this issue since that PR is much newer and should resolve it.
