### ISSUE TITLE
Old Clang version in WASI SDK 13

### ISSUE THREAD

**Issue by dasebek** [WebAssembly/wasi-sdk#203]
WASI SDK 12 came with clang version 11.0.0. WASI SDK 13 was released today, and it includes clang version 10.0.0. I downloaded and extracted `wasi-sdk-13.0-linux.tar.gz` from the releases page. I was expecting to see clang version 13.0.0 instead.

```
[david@fedora ~]$ /opt/wasi-sdk-12.0/bin/clang --version
clang version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: /opt/wasi-sdk-12.0/bin

[david@fedora ~]$ /opt/wasi-sdk-13.0/bin/clang --version
clang version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: /opt/wasi-sdk-13.0/bin
```

**Comment by sbc100** [comment]
Hmm .. that does look wrong.

Note that WASI SDK versioning is independent of llvm/clang versioning so that fact that wasi-sdk-13 is supposed to contain llvm-13.0.0 is just a coincidence.   It certainly shouldn't contain 10.0.0 though :(

**Comment by sbc100** [comment]
d32170dbd5b0d54436537b6b75beaf44324e0c28 is indeed the revision which is tagged as llvmorg-10.0.0 so this is not just clang being confused about which version it is.

**Comment by dasebek** [comment]
I think that submodules under https://github.com/WebAssembly/wasi-sdk/tree/wasi-sdk-13/src point to wrong/old commit numbers.

**Comment by sunfishcode** [comment]
It appears I made a mistake with git submodules and accidentally reverted the update to LLVM 13.0. I've now opened #204 to fix this. I'll plan to do a new wasi-sdk release once this is resolved.

**Comment by sunfishcode** [comment]
#205 fixes the git submodules and fixes a Windows build issue. When the build artifacts from the build on main are ready, I'll create a new release.

**Comment by availablish** [comment]
Is a ` wasi-sdk-14.0-linux.tar.gz` file coming? If that's the case I wait, in case it's not, how can I compile your sources? Just `make`? Any important `make` flag or env variable to be aware of? The install instructions of your README is based on directly downloading the linux file.

**Comment by sunfishcode** [comment]
You can download the artifacts straight from [the CI build](https://github.com/WebAssembly/wasi-sdk/actions/runs/1478956871#artifacts) if you'd like to download them now. These are the artifacts that I'll be attaching to the release once I sort out some minor issues around getting `git-describe` to output the right thing.

For example, on that page, click on dist-ubuntu-latest or dist-ubuntu-xenial to download a zip file containing the Linux wasi-sdk build.

**Comment by sunfishcode** [comment]
Ok, the artifacts are now attached to the [wasi-sdk-14 release](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-14). Please let me know if there are any further problems!

**Comment by availablish** [comment]
Perfect! Thank you. I'm using the new build without any issue now :)
