### ISSUE TITLE
c assert fail: unreachable

### ISSUE THREAD

**Issue by andersson09** [WebAssembly/wasi-sdk#210]
Hey,

Not exactly sure if this is the best place to post but I'm running a simple c test compiled to wasm using wasi-sdk-14.0:

```
#include <assert.h>

int main( int argc, char *argv[] )  
{
    assert(1 == 2);
}
```

Running this with wasmtime produces an unreachable error. The same program compiled with emscripten is fine.

On the readme it states "This repository does not yet support C++ exceptions", is this also related to issue above with c?

Thanks!

**Comment by andersson09** [comment]
Hmm, thinking about it more I think the wasi-sdk is correct, emsdk is incorrect and I'd probably expect wasmtime to handle the abort gracefully.

**Comment by sunfishcode** [comment]
When I try this, wasmtime does handle this reasonably gracefully, including printing a stack trace.

**Comment by andersson09** [comment]
I'm getting" Error: failed to run main module..." with "wasm trap unreachable". Seems a bit intense for a failed assert.

**Comment by sunfishcode** [comment]
Makes sense; I've now submitted bytecodealliance/wasmtime#3568 to make the wording a little more descriptive. Does describing it as the "wasm `unreachable` instruction" help clarify it?

**Comment by andersson09** [comment]
Sounds good.

**Comment by sunfishcode** [comment]
I believe the question here is no answered!
