### ISSUE TITLE
multi-memory support

### ISSUE THREAD

**Issue by thewtex** [WebAssembly/wasi-sdk#211]
Hi there,

Any thoughts on when, how, why, and example code to use the [multi-memory](https://github.com/WebAssembly/multi-memory/blob/master/proposals/multi-memory/Overview.md) support with wasi-sdk from C/C++?

**Comment by sunfishcode** [comment]
In LLVM, wasm's multi-memory could in theory be modeled as address spaces. In theory, multi-memory used this way could give programs some amount of isolation, where they could be sure that pointers into one memory won't ever accidentally overflow into another. Or, one memory could be exported and another not, providing somewhat more encapsulation than just exporting all of memory. That said, as far as I'm aware, support in LLVM for these kinds of use cases isn't very developed right now.

The main uses for multi-memory today that I'm aware of involve linking wasm modules together, outside of the source language toolchain. For example, [wasmlink](https://github.com/bytecodealliance/wai-bindgen/tree/main/crates/wasmlink) uses multi-memory.

**Comment by abrown** [comment]
I'll close this since I believe the question is answered; feel free to reopen if you have more questions!
