### ISSUE TITLE
zlib.h not found

### ISSUE THREAD

**Issue by orangeSi** [WebAssembly/wasi-sdk#214]
Hello, how can I  get the zlib.h for ```wasi-sdk```?
```
$../wasi-sdk-14.0/bin/clang seqtk.c -o seqtk.byclang.wasm
seqtk.c:31:10: fatal error: 'zlib.h' file not found
#include <zlib.h>
         ^~~~~~~~
1 error generated.
```

The ```emcc``` solve this problem by ```emcc x.c -o x.wasm -s USE_ZLIB=1``

**Comment by sunfishcode** [comment]
wasi-sdk is currently just a distribution of clang, wasi-libc, and supporting scripts. It does not currently include zlib.
