### ISSUE TITLE
Is it possible to have a windows MSVC release?

### ISSUE THREAD

**Issue by xujuntwt95329** [WebAssembly/wasi-sdk#215]

**Comment by sbc100** [comment]
Can you explain what you mean that exactly?   Are you talking about being able to build wasi programs from with MSVC, or a windows toolchain that was is compiled with MSVC rather than MINGW?  Or something else?

**Comment by xujuntwt95329** [comment]
Thanks for the quick reply. 

I mean a windows toolchain that was is compiled with MSVC rather than MINGW.

**Comment by sbc100** [comment]
I'm not familiar with the reason why that would be preferable to the one that we already ship built with MINGW.. can you explain why the existing one falls short?

**Comment by xujuntwt95329** [comment]
Well, It is not a hard requirement, just curious about the MSVC build because I just build a lldb on Windows and the official document uses the MSVC.

The MINGW release works well. I'll close this issue.

Thanks for your reply !
