### ISSUE TITLE
How to use inline-asm when compiling C to WebAssembly?

### ISSUE THREAD

**Issue by bathtub-01** [WebAssembly/wasi-sdk#216]
The compilation target I use is `wasm32-unknown-wasi`.

Although I didn't find any relevant documents, I found that inline-asm can be used to insert wasm code to C code. For example, I can write a function like this:
```C
void foo(){
  asm("i32.const 123 \n\t"
      "drop");
}
```
And clang **did** compile this code correctly.

Further, I wonder if I can use C variables in wasm inline-asm just like the normal way of x86 inline-asm?
I have tried to write something like:
```C
int foo(){
  int ret = 0;
  asm("i32.const 123 \n\t"
      "local.set %0 \n\t":
      "=rm"(ret));
  return ret;
}
```
In this example, I tried to assign a value of 123 to the variable `ret`. As I know, wasm will treat `ret` as a local variable, so I use the `local.set` instruction.

But clang throwed an error:
> error: invalid operand in inline asm

Do you have any ideas on how to make this right?

Thanks for your attention.

**Comment by sbc100** [comment]
Support for inline asm in the WebAssembly backend is not very well tested and should probably be considered experimental at best.

Support for write standalone .s file, however, is fairly good so I would recommend that route unless you are interested in working on improving the inline asm support on the llvm side.   Here is an example of a standalone assembly used in emscripten: https://github.com/emscripten-core/emscripten/blob/main/system/lib/compiler-rt/stack_ops.S

**Comment by bathtub-01** [comment]
Thank you, that answers my question : )
