### ISSUE TITLE
Add binary release for Linux on Apple Silicon M1

### ISSUE THREAD

**Issue by talg** [WebAssembly/wasi-sdk#236]
I think an increasing number of us are running on Linux on Apple Silicon with Parallels in a VM, and support would be great. I can always build from source, but I would guess there will be plenty of others who will run into this.

There is already an issue for this on MacOS #221.

**Comment by sascha1337** [comment]
wen

**Comment by weiqingtangx** [comment]
Guys, do you have a plan for this?

**Comment by sbc100** [comment]
Instructions for building from source are in the README: https://github.com/WebAssembly/wasi-sdk

I don't know of anyone working on a linux arm64 build.  We build our images using github CI I guess it depends on when we can actions runing on arm64 linux.. or somebody could figure out to do a cross-compile on x86?

**Comment by sascha1337** [comment]
followup, needed

**Comment by talg** [comment]
https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/

**Comment by gzurl** [comment]
+1
In my case, I'm running a container on top of an Apple M1, so I'm missing the `-linux-arm64` flavor.

**Comment by gzurl** [comment]
More info: Building from sources from a linux-arm64 container (tried with `ubuntu:22.04` and bitnami/minideb) fails.

In both containers, the error message is:

```
/usr/bin/cc -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/ubuntu/Home/Workspace/VMware/wasi-sdk/build/llvm/lib/Support/BLAKE3 -I/home/ubuntu/Home/Workspace/VMware/wasi-sdk/src/llvm-project/llvm/lib/Support/BLAKE3 -I/home/ubuntu/Home/Workspace/VMware/wasi-sdk/build/llvm/include -I/home/ubuntu/Home/Workspace/VMware/wasi-sdk/src/llvm-project/llvm/include -fPIC -Os -DNDEBUG -mavx512vl -MD -MT lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o -MF lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o.d -o lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o -c /home/ubuntu/Home/Workspace/VMware/wasi-sdk/src/llvm-project/llvm/lib/Support/BLAKE3/blake3_avx512_x86-64_unix.S
cc: error: unrecognized command-line option '-mavx512vl'
```

Any insight about how to workaround this? Thanks!

**Comment by abrown** [comment]
This issue is open for anyone to work on: from what I can tell, it would involve modifying the CI workflow, the CI scripts, and (perhaps) the Makefile.

**Comment by JaydenElliott** [comment]
+1 to a linux arm64 release. I'm running directly on a linux machine and it takes 60+ mins to compile llvm. 

If no one picks the ticket up i'll give it a go.

**Comment by jasonwashburn** [comment]
I started looking into this, locally the build went fine, and editing the ci workflows/scripts is straight forward. I think the bigger potential hold back here is where it would run. From what I can tell, Github currently only provides m1 runners in their "larger" runners offerings, which can get pricey. Other option could be self-hosted runners. Thoughts?

**Comment by justdan96** [comment]
MacStadium provides native Mac runners for open source projects.

**Comment by dicej** [comment]
Per my comment in #347, I'm planning to work on this soonish.  If we can't use a native runner for whatever reason, we can cross-compile, potentially.  I'll look into it.

**Comment by aykevl** [comment]
According to [GitHub docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#larger-runners), it appears that ARM based runners are only available for paying customers.

Looking forward to having wasi-sdk on linux/arm64 though!

**Comment by jasonwashburn** [comment]
Yeah, I noticed the documentation doesn't seem really clear on that...but I remember seeing the news article come out a while back about them releasing m1 runners free for open source projects...and this seems to indicate the same as well https://github.com/actions/runner-images/issues/9254

**Comment by alexcrichton** [comment]
I believe this is done now in https://github.com/WebAssembly/wasi-sdk/pull/429, so closing.
