### ISSUE TITLE
wasi-ld now links libxml2 but it is not in wasi-sdk

### ISSUE THREAD

**Issue by pvetere** [WebAssembly/wasi-sdk#243]
Testing on a container with minimal packages.  I installed wasi-sdk 16.0, set it in my $PATH, and compiled a simple C program to wasm (https://github.com/singlestore-labs/singlestore-wasm-toolkit/tree/main/examples/cpp/power).  Compilation failed with:

```
clang++                             \
    -fno-exceptions                 \
    --target=wasm32-unknown-wasi    \
    -mexec-model=reactor            \
    -s                              \
    -I.                             \
    -o split.wasm                   \
    split.cpp
/opt/wasi-sdk/bin/wasm-ld: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory
clang-14: error: unable to execute command: No such file or directory
clang-14: error: linker command failed due to signal (use -v to see invocation)
make: *** [Makefile:4: split.wasm] Error 255
```

The test program doesn't use libxml2 at all, so I'm guessing wasi-ld is implicitly trying to include it.  Indeed, when I installed the libxml2-dev package into my container, compilation was successful.

One more data point -- this compilation succeeded in wasi sdk 14.0.

Does libxml2 now need to be included in wasi sdk?

**Comment by sbc100** [comment]
Yes, this is a dependency of LLVM.  When we build the emscripten version we disable this with: `-DLLVM_ENABLE_LIBXML2=OFF`": https://chromium.googlesource.com/emscripten-releases/+/main/src/build.py#757

I'm don't know off hand what features of LLVM this disables, but I would guess its nothing critical can we should also pass this flag when building wasi-sdk.

**Comment by sbc100** [comment]
The quickest fix you would would be to install libxml2 on the host machine where you are installing wask-sdk.

**Comment by sunfishcode** [comment]
I've now submittted #244 to set `LLVM_ENABLE_LIBXML2=OFF`.
