### ISSUE TITLE
wasi-sdk and bazel

### ISSUE THREAD

**Issue by GOVYANSONG** [WebAssembly/wasi-sdk#252]
Is there any guidance on using bazel to build wasi target with c/c++ project? I read about emscripten and rust. Just wonder if something substantial has been done on this front.

**Comment by sbc100** [comment]
I'm not aware of any bazel rules for wasi-sdk.  However, if anyone wants to contribute them I imagine this would be the right repo.   I imagine they would be fair amount simper than the emscripten ones that live in the emsdk repo.

**Comment by GOVYANSONG** [comment]
my environment is ubuntu 20.04, gcc and clang. i have multiple version of clang in the box. to be able to use a specific version, i created a custom cc toolchain by following instructions given at https://bazel.build/tutorials/ccp-toolchain-config. Basically, one just needs to set up compiler options. you can do that in cc_binary rule with copts attribute.
