### ISSUE TITLE
Update to LLVM 15

### ISSUE THREAD

**Issue by oSoMoN** [WebAssembly/wasi-sdk#258]
Similar to 7b7b8a974a31f527d71467499b0d5be3b12f2fa9. LLVM 15.0 was released 2.5 months ago, and the current stable release is 15.0.5.

**Comment by sunfishcode** [comment]
The current blocker is a build error on Windows: https://github.com/WebAssembly/wasi-sdk/pull/255.

**Comment by brettcannon** [comment]
I think this can be closed as I believe https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-19 came with LLVM 15.

**Comment by sunfishcode** [comment]
Yep, thanks!
