### ISSUE TITLE
Binary assets for Release 17

### ISSUE THREAD

**Issue by ringoz** [WebAssembly/wasi-sdk#268]
Some assets for release 17 have strange names like [wasi-sdk-17.15gb738c9d55304+m-mingw-x86.tar.gz](https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sdk-17.15gb738c9d55304+m-mingw-x86.tar.gz)
This is unfortunate for automating the downloads, previous releases were named better (e.g. wasi-sdk-16.0-mingw.tar.gz)

**Comment by sunfishcode** [comment]
Good idea. I've now updated them as [wasi-sdk-17.0-mingw.tar.gz](https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sdk-17.0-mingw.tar.gz).

**Comment by ringoz** [comment]
there is still folder named "wasi-sdk-16.15gb738c9d55304+m" inside new archive

**Comment by ringoz** [comment]
once again naming is inconsistent...
