### ISSUE TITLE
Use with rust's bindgen

### ISSUE THREAD

**Issue by HKalbasi** [WebAssembly/wasi-sdk#269]
I want to build a Rust project with some C/C++ dependency for `wasm32-wasi` target. The project has a `build.rs` script, which builds the C project with cmake and then generates bindings with `bindgen` crate. The cmake part works with `wasi-sdk` compiler and it finishes successfully, but the bindgen part fails with `fatal error: 'stdio.h' file not found` error. If I understand correctly, I should use a `libclang.so` from `wasi-sdk` for using in bindgen, but how I can build that? The released debian package doesn't have it I think.

**Comment by sunfishcode** [comment]
I don't know the best way to do this, but here's what I know.

wasi-sdk doesn't have any patches; it's just a build of upstream clang and related things. So there's a change that you don't need to use a special libclang.so. If your clang has the wasm32 target in it, it's probably enough.

For `stdio.h`, the wasi-sdk releases have a sysroot tarball which contains that and the other headers you'll likely need:
 - https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sysroot-17.0.tar.gz

It may be possible to point clang at that header using the `--sysroot <path>` option.

You may also need a libclang_rt.builtins library; the download for that is:
 - https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/libclang_rt.builtins-wasm32-wasi-17.0.tar.gz

**Comment by sbc100** [comment]
All the this unsupported options are linker flags.  That can be passed via clang if you use the `-Wl,` prefix, or they can be passed directly to wasm-ld.

Regarding the missing `-lstdc++`, this is because wasi-sdk includes libc++ from llvm and not libstd++ from GNU.    Do you who is injecting `-lstdc++`?   Clang itself should know to use `-lc++` instead of `-lstdc++` when linking with `clang++`.

**Comment by sbc100** [comment]
If you are running wasm-ld directly (not recommend, for these kinds of reason) then you will need to have `-L` flags to point into the wasi sysroot so it can find those libraries.  

If you can its better to use `clang++` to do the linking for you and then it will add the correct `-L` and `-lc++` for you.

**Comment by HKalbasi** [comment]
Thanks! I didn't found out how to make it work with `clang++ -Wl`, but `wasm-ld` worked with this config:
```
[target.wasm32-wasi]
linker = "/opt/wasi-sdk/bin/wasm-ld"
rustflags = ["-C", "link-args=-L /opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi"]
```
