### ISSUE TITLE
cmake toolchain file for wasm32-wasi-pthread

### ISSUE THREAD

**Issue by yamt** [WebAssembly/wasi-sdk#272]
currently `wasi-sdk.cmake` has `set(triple wasm32-wasi)`.
there needs a way to use `set(triple wasm32-wasi-pthread)` for threaded apps.

also, `set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")` is required to pass the cmake compiler test (`CMakeTestCCompiler.cmake`) for `wasm32-wasi-pthread`.

a straightforward solution is to have a separate cmake toolchain file, say `wasi-sdk-pthread.cmake` for threaded apps.

**Comment by abrown** [comment]
I think is closed by #274.
