### ISSUE TITLE
wasm-ld: error: unable to find library -lstdc++

### ISSUE THREAD

**Issue by dstaley** [WebAssembly/wasi-sdk#276]
I'm attempting to compile a non-trivial application written in Rust and using a large number of external libraries to WASM, and am encountering the following error:

> wasm-ld: error: unable to find library -lstdc++

Looking at the log, `stdc++` is only present after a file that originates from the `wasm32-wasi` toolchain:

```
"/usr/local/rustup/toolchains/1.66.0-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-wasi/lib/libcompiler_builtins-d747d107c1fad665.rlib" "-l" "stdc++" "-l" "c"
```

I'll be the first to admit this is probably a trivial error, but after a decent chunk of searching I wasn't able to find anyone else experiencing this specific issue in combination with Rust and WASI.

I'm using the following environment variables:
```
WASI_SYSROOT=/usr/wasi-sdk-16.0/share/wasi-sysroot
CC_wasm32_wasi=/usr/wasi-sdk-16.0/bin/clang
CARGO_TARGET_WASM32_WASI_LINKER=/usr/wasi-sdk-16.0/bin/clang
```

**Comment by sbc100** [comment]
I don't know that anyone has posrted libstc++ (the GNU C++ library) to wasm.   For wasi-sdk you want to link with `-lc++`  (the llvm C++ library) instead.

**Comment by dstaley** [comment]
Ah thank you! This pushed me to investigate a bit more, and I discovered that one of my deps was manually invoking `cc` to determine the availability of libstdc++, which was present on my system since I was using Linux. Gonna close this since it appears to be an issue with my specific dependency versus wasi-sdk.
