### ISSUE TITLE
Fully static linux distribution?

### ISSUE THREAD

**Issue by TerrorJack** [WebAssembly/wasi-sdk#280]
It's possible to build a `wasi-sdk` linux distribution with fully static executables, so they work out of the box regardless of host system's glibc version. The fully static distribution can be provided as a `-musl` variant in addition to existing glibc-based variant.

I've been building and using fully static `wasi-sdk` in GHC's fork for some time and haven't encountered issues so far, so just asking if `wasi-sdk` maintainers find this a worthy idea, in that case I can contribute the pipeline to build it :)

**Comment by sbc100** [comment]
Out of interest, what is the distro you are trying to run on where the existing binaries don't work?

**Comment by TerrorJack** [comment]
@sbc100 None; the task of decoupling dependency on host glibc just happened to be a low hanging fruit for me, and it's especially convenient for NixOS, no need to `patchelf` anymore.

A more realistic concern is: upstream linux distribution is built on `ubuntu-latest` which itself is a moving target (although very slowly). Currently it's `ubuntu-22.04`, and people may be angry that the linux distribution stop working on older versions, even EOL ones. #273 is one such example, but I think that compared to sticking to an arbitrarily old glibc version, simply providing a distribution that doesn't rely on glibc sounds better.

**Comment by sbc100** [comment]
> but I think that compared to sticking to an arbitrarily old glibc version, simply providing a distribution that doesn't rely on glibc sounds better.

I can see pros and cons to both, and perhaps we should do both.  In general I think its preferable to have smaller, dynamically linked set of binaries that play nice with glibc-based distributions (which are in a the vast majority).   We could provide a musl-based statically linked set in addition but I would hope that a tiny minority of linux users would never need to use it. 

I also don't think its the job of wasi-sdk itself (the github project) to publish binaries that run on every single OS/distro combination.. downstream distros do their own packaging and we should lean on that when it makes sense.

**Comment by sbc100** [comment]
> @sbc100 None; the task of decoupling dependency on host glibc just happened to be a low hanging fruit for me, and it's especially convenient for NixOS, no need to `patchelf` anymore.
> 

Out of interest, for NixOS do you not do your own downstream packaing/building?  You consume the binaries we publish?

**Comment by TerrorJack** [comment]
> You consume the binaries we publish?

Nope, we don't use upstream `wasi-sdk` since there are other modifications in our fork. But indeed we only build for x64 linux once, and reuse that artifact for NixOS.

> I also don't think its the job of wasi-sdk itself (the github project) to publish binaries that run on every single OS/distro combination

Yes, that makes sense! I'll hold off for the time being then.
