### ISSUE TITLE
Release process should be documented

### ISSUE THREAD

**Issue by yamt** [WebAssembly/wasi-sdk#284]
or even automated.

at least it should be clear where release asserts came from.

cf. https://github.com/WebAssembly/wasi-libc/issues/326#issuecomment-1362055334

**Comment by thewtex** [comment]
Heads up, the assets are currently missing from wasi-sdk-18: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-18

**Comment by sunfishcode** [comment]
That's because I haven't done the manual steps yet :-}. Also, there's a regression being discussed in https://github.com/WebAssembly/wasi-libc/pull/377, which only affects users using -Wl,--initial-memory, and there's a possibility we may do another release soon to fix it.

**Comment by yamt** [comment]
> manually download the artifacts from the latest CI build

@TerrorJack suggested to use linux artifacts from docker job: https://github.com/WebAssembly/wasi-sdk/pull/273#issuecomment-1373879491
is it what you do?

**Comment by yamt** [comment]
> I download the artifacts from a CI run, such as here: https://github.com/WebAssembly/wasi-sdk/actions/runs/3889687857#artifacts

do you mean to include binary from both of dist-ubuntu-bionic and dist-ubuntu-latest?

**Comment by sunfishcode** [comment]
I look at the artifacts from the previous release and try to upload the same artifacts.

**Comment by TerrorJack** [comment]
@sunfishcode It seems the `dist-ubuntu-latest` artifact has been the choice of the linux binary release for the past few releases. It may also be good to also upload `dist-ubuntu-bionic` and name it something like ` wasi-sdk-19.0-ubuntu-bionic.tar.gz `, and mention it in the release notes, so when people want to use it in a distro with outdated glibc, they can choose it.
