### ISSUE TITLE
Link in README to Docker image returns a 404

### ISSUE THREAD

**Issue by brettcannon** [WebAssembly/wasi-sdk#291]
https://github.com/WebAssembly/wasi-sdk/pkgs/container/wasi-sdk doesn't lead to anything. And going to https://github.com/orgs/WebAssembly/packages doesn't show any packages for anything.

**Comment by anuraaga** [comment]
Asked a few times without luck yet - can anyone tweak the org settings for this? It will really make wasi-sdk easier to use in various repos. Next library I want to try building is https://github.com/pganalyze/pg_query_go/tree/main/parser for example, and having an official image will make that a lot easier to propose.

https://github.com/WebAssembly/wasi-sdk/issues/289#issuecomment-1383314031

**Comment by sbc100** [comment]
I tried to change the settings for this package to "Public" but its says: 

```Public
Make this package visible to anyone.

 Setting is disabled by organization administrators.
```

**Comment by sbc100** [comment]
OK, I looks like the packages are now public.  @brettcannon can you confirm ?  (and close this issue).

**Comment by anuraaga** [comment]
Thanks @sbc100! Could confirm it works well

https://github.com/corazawaf/coraza-proxy-wasm/pull/146

**Comment by brettcannon** [comment]
All good! Thanks!
