### ISSUE TITLE
Demangle option does not work for wasi-ld

### ISSUE THREAD

**Issue by cngzhnp** [WebAssembly/wasi-sdk#292]
I have a simple functions written in `C++` and which could be used inside WASM application. 

However, when I call these functions from WASM application, functions cannot be found due to their mangled names which changed by linker itself normally. 

With help of `extern "C"` keyword, function names are not mangled anymore and could be found easily. However, I do not want to use this keyword and instead of that I prefer to use `"--demangle"` option from linker. 

In this case, here is the example C++ application contains two simple functions:

```cpp
#include <cstdio>
#include <cstdlib>

int calc_square(int temp1)
{
    return temp1 * temp1;
}

int calc_cube(int temp1)
{
    return calc_square(temp1) * temp1;
}
```

Afterwards, I compile this C++ file to generate output file from it with the following command:

`./clang++ --target=wasm32-unknown-wasi -O3 -Wall -Wextra -Werror -fno-exceptions --sysroot=../share/wasi-sysroot -std=gnu++20 -o try_demangle.cpp.o -c try_demangle.cpp`

Then I try to link generated output file to generate final WASM file with the following command:

`./wasm-ld --no-entry --export-all --demangle try_demangle.cpp.o -o try_demangle.wasm`

Then, here is the WAT format of this WASM file which was translated by `WASM2WAT` tool from `binaryen`:

`wasm2wat try_demangle.wasm -o try_demangle.wat`

**Result:**

```wasm
(module
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (func $__wasm_call_ctors (type 0))
  (func $calc_square_int_ (type 1) (param i32) (result i32)
    local.get 0
    local.get 0
    i32.mul)
  (func $calc_cube_int_ (type 1) (param i32) (result i32)
    local.get 0
    local.get 0
    i32.mul
    local.get 0
    i32.mul)
  (memory (;0;) 2)
  (global $__stack_pointer (mut i32) (i32.const 66560))
  (global (;1;) i32 (i32.const 1024))
  (global (;2;) i32 (i32.const 1024))
  (global (;3;) i32 (i32.const 1024))
  (global (;4;) i32 (i32.const 66560))
  (global (;5;) i32 (i32.const 131072))
  (global (;6;) i32 (i32.const 0))
  (global (;7;) i32 (i32.const 1))
  (export "memory" (memory 0))
  (export "__wasm_call_ctors" (func $__wasm_call_ctors))
  (export "_Z11calc_squarei" (func $calc_square_int_))
  (export "_Z9calc_cubei" (func $calc_cube_int_))
  (export "__dso_handle" (global 1))
  (export "__data_end" (global 2))
  (export "__global_base" (global 3))
  (export "__heap_base" (global 4))
  (export "__heap_end" (global 5))
  (export "__memory_base" (global 6))
  (export "__table_base" (global 7)))
```

As you can realize from above output, all function names are still mangled like `"_Z11calc_squarei"` and `"_Z9calc_cubei"`. 

**Expectation:**

Mangling of function names must be disabled if "`--demangle`" option was set for `wasi-ld`.

**Environment:**

```
clang version 15.0.7
Target: wasm32-unknown-wasi
Thread model: posix
```

**Comment by sbc100** [comment]
The `--demangle` option only effects the debug message printed by `wasm-ld` itself and the name section of the generated  wasm.   I'm not sure its good idea to expand this to also cover import/export names.    Can you explain your use case little more perhaps?  Do you really want to to have to have exports that contains brackets and types in their names (e.g. `calc_square(int)`)?

Another way to be more explicit about the export name is to use `__attribute__((export_name("calc_cube")))`.  

In any case, this issue would probably better files against wasm-ld itself, since its not really a wasi-sdk issue.

**Comment by cngzhnp** [comment]
Thanks for the quick reply! I was not aware of that, `demangle` option was only available for debug messages. I am also not pretty sure that it is a good idea to expand such a feature for release versions but I can explain my use case more precisely to decide whether does it make sense or not.

In my use case, these function names are pre-known by the user application. So, these function names will be looked up in the WAMR and they will be found out & called by their names, then the result will be taken out of it.

However, if the WASM file is generated without using `extern "C"` keyword for those functions, they will not be found by WAMR due to mangling. Moreover, from my perspective using such `"ugly keywords"` would make this implementation not-developer friendly. What is your opinion about that?

**Comment by abrown** [comment]
I think using the `export_name` attribute is the way to go here; @cngzhnp, if you do want to change the behavior of `--demangle` perhaps an issue to LLVM is more appropriate? I'll close this for now but feel free to reopen if I misunderstood something.
