### ISSUE TITLE
Build failure on AArch64 Ubuntu 20.04

### ISSUE THREAD

**Issue by sparker-arm** [WebAssembly/wasi-sdk#294]
Hi,

I've just updated the LLVM submodule, from 14 to 15, and now the wasi-sdk build is failing. It looks like it's trying to build something very much x86 specific:

lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o 
/usr/bin/cc -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support/BLAKE3 -I~/src/WebAssembly/wasi-sdk/src/llvm-project/llvm/lib/Support/BLAKE3 -Iinclude -I~/src/WebAssembly/wasi-sdk/src/llvm-project/llvm/include -fPIC -Os -DNDEBUG   -mavx512vl -MD -MT lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o -MF lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o.d -o lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o -c ~/src/WebAssembly/wasi-sdk/src/llvm-project/llvm/lib/Support/BLAKE3/blake3_avx512_x86-64_unix.S
cc: error: unrecognized command line option ‘-mavx512vl’

**Comment by sbc100** [comment]
FWIW, the flag looks like its coming from here: https://github.com/llvm/llvm-project/blob/079c488c66056f7bf22c30ee280489f6c43b7658/llvm/lib/Support/BLAKE3/CMakeLists.txt#L69-L71

**Comment by sparker-arm** [comment]
Ah, sorry!
```
$ cc --version
cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

I'm just using all the defaults, and calling `make build`.

**Comment by sbc100** [comment]
This looks like some kind of llvm configuration issue.     The whole block that adds `-mavx512vl` and `blake3_avx512_x86-64_unix.S` should be x86_64 only.   If you are building with an arm64 version of gcc I don't think those should even be included.

**Comment by sparker-arm** [comment]
Indeed. I went through the CMake config and the only thing that looked suspicious was the OSX settings [here](https://github.com/WebAssembly/wasi-sdk/blob/7ef7e948fa8c12e61c78b9584b29b7a41c611740/Makefile#L64). Removing this line fixes the issue, but unfortunately I'm not in the position to create a PR.

**Comment by sbc100** [comment]
That interesting.   Seems like a bug in the llvm build system that `-DCMAKE_OSX_ARCHITECTURES` does anything at all when building on linux.

I guess we can work around it downstream by finding a way to only pass this argument when actual running on macOS.

**Comment by TerrorJack** [comment]
I can build on aarch64 alpine linux and `-DCMAKE_OSX_ARCHITECTURES` don't seem to be a problem: https://gitlab.haskell.org/ghc/wasi-sdk/-/jobs/1361963

**Comment by gzurl** [comment]
I can confirm that removing the `-DCMAKE_OSX_ARCHITECTURES` line [from Makefile](https://github.com/WebAssembly/wasi-sdk/blob/7ef7e948fa8c12e61c78b9584b29b7a41c611740/Makefile#L64) (as pointed by @sparker-arm) solves the issue on Ubuntu 22.04 arm64.

**Comment by sbc100** [comment]
I wonder if this is maybe something that was fixed upstream in llvm, or should be?  Could somebody confirm if this issue also occurs with llvm `main`?

**Comment by sparker-arm** [comment]
I was going to say that I've never had a problem building LLVM on my system, but then I remembered that I use clang :)

But double-checking with the default system toolchain (ubuntu gcc-9.4.0), I have no problems building 15.0.7 and main.

Building LLVM doesn't set `CMAKE_OSX_ARCHITECTURES`, at least not on Linux. I guess we just need to check `IS_X64` [here](https://github.com/llvm/llvm-project/blob/079c488c66056f7bf22c30ee280489f6c43b7658/llvm/lib/Support/BLAKE3/CMakeLists.txt#L70).

**Comment by johalun** [comment]
I got this error and another compile error later on when using GCC. No issues at all when using clang.

**Comment by matsbror** [comment]
I think this is handled by https://github.com/WebAssembly/wasi-sdk/pull/321

**Comment by abrown** [comment]
I'll close this because I think @matsbror is right in that this issue is closed. If for some reason it is not, we can always reopen it.
