### ISSUE TITLE
The Linux clang binary in wasi-sdk-20+threads release is fantastically cursed

### ISSUE THREAD

**Issue by whitequark** [WebAssembly/wasi-sdk#300]
If you run it, it segfaults:

```
$ ./wasi-sdk-19.0/bin/clang++ --version
clang version 15.0.7
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: /home/whitequark/Projects/yowasp/nextpnr/./wasi-sdk-19.0/bin
$ ./wasi-sdk-20.0+threads/bin/clang++ --version 
Segmentation fault
```

If you run it under gdb, gdb breaks:

```
$ gdb --quiet --args ./wasi-sdk-20.0+threads/bin/clang-16 --version
"0x7ffcfc1ce650s": not in executable format: file format not recognized
(gdb)
```

If you look at it, it looks really weird:

```
$ file -L ./wasi-sdk-19.0/bin/clang++ 
./wasi-sdk-19.0/bin/clang++: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=3b2817eb45d389450bc034cf206408503ae5a6df, stripped
$ file -L ./wasi-sdk-20.0+threads/bin/clang++ 
./wasi-sdk-20.0+threads/bin/clang++: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, missing section headers
```

![Screenshot_20230223_041725](https://user-images.githubusercontent.com/54771/220820346-75796917-ed8b-42d8-bb32-6f71afcd0c8d.png)

No executable code at all!

<details>
<summary>For comparison this is how a normal binary looks like</summary>

![Screenshot_20230223_041805](https://user-images.githubusercontent.com/54771/220820420-5d0088d4-7221-493c-a812-64e6faa3ca49.png)
</details>

(Does the CI run the built artefacts at all before releasing them?)

**Comment by whitequark** [comment]
Okay, I redownloaded the archive and now it's fine. I think the binary got truncated somehow and it looks like Linux tooling really doesn't handle that case well?

**Comment by abrown** [comment]
Phew, glad you figured out the issue!
