### ISSUE TITLE
WASM module load failed: integer too large

### ISSUE THREAD

**Issue by Photosounder** [WebAssembly/wasi-sdk#319]
I'm posting this in this repo because this is most likely a wasi-sdk problem. I switched from compiling WASM with emcc to compiling with `/opt/wasi-sdk/bin/clang` and this is what I get when I try to run `wasm_runtime_load()` on my WASM file: `WASM module load failed: integer too large`.

Here's the WASM compilation command:
```
/opt/wasi-sdk/bin/clang \
    -I/home -Wno-incompatible-pointer-types -Wno-dangling-else -Wno-parentheses -Wno-pointer-sign -Wno-shift-op-parentheses -Wno-tautological-pointer-compare \
    -Os -pthread -nostdlib -z stack-size=32768      \
    -Wl,--shared-memory             \
    -Wl,--initial-memory=131072,--max-memory=131072 \
    -Wl,--no-entry -Wl,--export=plugin_draw                \
    -Wl,--export=__heap_base,--export=__data_end    \
    -Wl,--export=__wasm_call_ctors  \
    test.c -o test.wasm
```

And here's `test.c` in case that matters:
```
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>

void plugin_draw(uint32_t *fb)
{
	int iy, ix;
	static int it = 0;

	for (iy=0 ; iy < 512; iy++)
		for (ix=0 ; ix < 512; ix++)
			fb[iy*512 + ix] = ((it*512+iy)*512 + ix) * 0x12321;

	it++;
}
```

Here's the `test.wasm` file in case anyone needs a quick look:
[test.wasm.zip](https://github.com/WebAssembly/wasi-sdk/files/11116176/test.wasm.zip)

**Comment by abrown** [comment]
What engine gave you the `integer too large` error? And was it related to the memory size in some way? I saw this earlier but didn't have enough detail to understand what was going on. Should we close?

**Comment by Photosounder** [comment]
I use the defaults so I don't know which engine that is, here's the relevant loading code:

```c
ctx.stack_size = 1420 + 1024;
ctx.heap_size = 1024*1024+9;

// Init runtime
if (!wasm_runtime_init())
{
	fprintf(stderr, "Init runtime environment wasm_runtime_init() failed.\n");
	return;
}

// Register native functions
if (!wasm_runtime_register_natives("env", native_symbols, sizeof(native_symbols) / sizeof(NativeSymbol)))
{
	fprintf(stderr, "Register native functions wasm_runtime_register_natives() failed.\n");
	return;
}

// Load WASM file
buffer_t wasm_buf = buf_load_raw_file("test.wasm");

ctx.module = wasm_runtime_load(wasm_buf.buf, wasm_buf.len, ctx.error_buf, sizeof(ctx.error_buf));
if (!ctx.module)
{
	fprintf(stderr, "Load wasm module wasm_runtime_load() failed. error: %s\n", ctx.error_buf);
	return;
}
```

**Comment by abrown** [comment]
By "engine" I mean: V8? Wasmtime? WAMR? There's a few others but hopefully you get what I'm asking. It sounds to me like one of those engines may have a problem, not wasi-sdk, so we could close the issue here and continue the discussion in whichever engine repository this applies to.

**Comment by Photosounder** [comment]
Ah I see, I'm using WAMR.

**Comment by abrown** [comment]
cc: @wenyongh, what do you think about this?

**Comment by wenyongh** [comment]
@Photosounder Please enable shared memory while building WAMR if you compile the wasm app with `-Wl,--shared-memory` flag: build with `cmake -DWAMR_BUILD_SHARED_MEMORY=1` or `cmake -DWAMR_BUILD_LIB_PTHREAD=1`

**Comment by Photosounder** [comment]
If the problem is not having compiled with shared memory enabled maybe it could say so instead of only cryptically saying "integer too large".

**Comment by abrown** [comment]
I think we can close this here and continue the discussion over on the WAMR repository. @Photosounder, I would guess a PR to WAMR would be appreciated to improve the error message.
