### ISSUE TITLE
-Wl,--no-entry doesn't work when -nostdlib is absent

### ISSUE THREAD

**Issue by Photosounder** [WebAssembly/wasi-sdk#320]
When I compile a simple file with this command: `/opt/wasi-sdk/bin/clang -Wl,--no-entry test.c -o test.wasm -v`
I get this:
```
clang version 16.0.0
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: C:/msys/opt/wasi-sdk/bin
 "C:/msys/opt/wasi-sdk/bin/clang.exe" -cc1 -triple wasm32-unknown-wasi -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -dis
card-value-names -main-file-name test.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu gen
eric -fvisibility=hidden -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=C:/msys/home/exp/wasm_app -resource-di
r C:/msys/opt/wasi-sdk/lib/clang/16 -isysroot C:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot -internal-isystem C:/msys/opt/wasi-sdk/lib/clang/16/include -intern
al-isystem C:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot/include/wasm32-wasi -internal-isystem C:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot/include -fdebug-c
ompilation-dir=C:/msys/home/exp/wasm_app -ferror-limit 19 -fmessage-length=160 -fgnuc-version=4.2.1 -fcolor-diagnostics -o C:/msys/tmp/test-649c5d.o -x c test.c
clang -cc1 version 16.0.0 based upon LLVM 16.0.0 default target wasm32-wasi
ignoring nonexistent directory "C:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot/include/wasm32-wasi"
#include "..." search starts here:
#include <...> search starts here:
 C:/msys/opt/wasi-sdk/lib/clang/16/include
 C:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot/include
End of search list.
 "C:/msys/opt/wasi-sdk/bin/wasm-ld" -m wasm32 -LC:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot/lib/wasm32-wasi C:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot/li
b/wasm32-wasi/crt1-command.o --no-entry C:/msys/tmp/test-649c5d.o -lc C:/msys/opt/wasi-sdk/lib/clang/16/lib/wasi/libclang_rt.builtins-wasm32.a -o test.wasm
wasm-ld: error: C:/msys/opt/wasi-sdk/bin/../share/wasi-sysroot/lib/wasm32-wasi/libc.a(__main_void.o): undefined symbol: main
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Adding `-nostdlib` fixes this, however, and I guess it's to be expected, if I try to compile a less simple file the linker complains about symbols like `realloc`, `stderr` or `free` being amiss.

So despite `-Wl,--no-entry` being specified I am forced to provide an empty `main()` function.

**Comment by sbc100** [comment]
I think you can use `-nostartfiles` along with `-Wl,--no-entry` to avoid linking `crt1-command.o` but continue to include libc and other libraries.

I believe this is no different to how clang or gcc work on native platforms.

**Comment by Photosounder** [comment]
If I use `-nostdlib /opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi/libc.a` it works correctly. Is this even the correct way to add the libc? It's hard to tell, I haven't found much documentation about what we're supposed to do. Where's the relevant documentation?

**Comment by sbc100** [comment]
I think `-nostartfiles` is what you want.    If you do want to link against libc explicitly you can just use `-lc` I believe, but that should not be necessary if you use `-nostartfiles`.

**Comment by Photosounder** [comment]
> I think you can use `-nostartfiles` along with `-Wl,--no-entry` to avoid linking `crt1-command.o` but continue to include libc and other libraries.
> 
> I believe this is no different to how clang or gcc work on native platforms.

OK I removed what I put in my previous post and only have `-nostartfiles` and now everything works correctly. I've never seen that option anywhere before though. Maybe this should be documented for people like me who don't just know.

**Comment by sbc100** [comment]
These are gcc flags, which clang implements and wasi-sdk inherits.  From the gcc man page:

```
       -nostartfiles
           Do not use the standard system startup files when linking.  The standard system libraries are
           used normally, unless -nostdlib, -nolibc, or -nodefaultlibs is used.

       -nodefaultlibs
           Do not use the standard system libraries when linking.  Only the libraries you specify are
           passed to the linker, and options specifying linkage of the system libraries, such as
           -static-libgcc or -shared-libgcc, are ignored.  The standard startup files are used normally,
           unless -nostartfiles is used.

           The compiler may generate calls to "memcmp", "memset", "memcpy" and "memmove".  These entries
           are usually resolved by entries in libc.  These entry points should be supplied through some
           other mechanism when this option is specified.

       -nolibc
           Do not use the C library or system libraries tightly coupled with it when linking.  Still link
           with the startup files, libgcc or toolchain provided language support libraries such as
           libgnat, libgfortran or libstdc++ unless options preventing their inclusion are used as well.
           This typically removes -lc from the link command line, as well as system libraries that
           normally go with it and become meaningless when absence of a C library is assumed, for example
           -lpthread or -lm in some configurations.  This is intended for bare-board targets when there is
           indeed no C library available.

       -nostdlib
           Do not use the standard system startup files or libraries when linking.  No startup files and
           only the libraries you specify are passed to the linker, and options specifying linkage of the
           system libraries, such as -static-libgcc or -shared-libgcc, are ignored.

           The compiler may generate calls to "memcmp", "memset", "memcpy" and "memmove".  These entries
           are usually resolved by entries in libc.  These entry points should be supplied through some
           other mechanism when this option is specified.

           One of the standard libraries bypassed by -nostdlib and -nodefaultlibs is libgcc.a, a library
           of internal subroutines which GCC uses to overcome shortcomings of particular machines, or
           special needs for some languages.

           In most cases, you need libgcc.a even when you want to avoid other standard libraries.  In
           other words, when you specify -nostdlib or -nodefaultlibs you should usually specify -lgcc as
           well.  This ensures that you have no unresolved references to internal GCC library subroutines.
           (An example of such an internal subroutine is "__main", used to ensure C++ constructors are
           called.)
```

Perhaps we could document this stuff somewhere in a wasi-sdk FAQ or readme.. perhaps under "reactors"?

**Comment by Photosounder** [comment]
I had no idea. Yes making tutorial-like documentation for reactors would be helpful, like, how to make a typical reactor.

**Comment by Photosounder** [comment]
I just noticed that when I compile with this:
`/opt/wasi-sdk/bin/clang -I/home -Wno-incompatible-pointer-types -Wno-dangling-else -Wno-parentheses -Wno-pointer-sign -Wno-shift-op-parentheses -Wno-tautological-pointer-compare -Wl,--no-entry -Wl,--export=plugin_draw -nostartfiles -mexec-model=reactor -Os test.c -o test.wasm`

I still get this when running my host:
`[18:52:56:342 - 7FFEB892B7C0]: warning: a module with WASI apis should be either a command or a reactor`
Even though there's no main() function.

**Comment by sbc100** [comment]
IIRC if you do `-mexec-model=reactor` does't clang take care of defining the `_initialize` as the entry point?  In that case I don't think you want `-Wl,--no-entry`?  

I imagine the warning is because the runtime doesn't see `_initialize` being exported?

**Comment by Photosounder** [comment]
Well if I remove `-Wl,--no-entry` and keep `-mexec-model=reactor` I get this:
`wasm-ld: error: entry symbol not defined (pass --no-entry to suppress): _initialize`

**Comment by sbc100** [comment]
You need to remove `-nostartfiles` since its the crt1 (start file) that defines `_initialize`
