### ISSUE TITLE
wasm-ld: error: unable to find library -lvsomeip3

### ISSUE THREAD

**Issue by Anilkumar1818** [WebAssembly/wasi-sdk#330]
# Copyright (C) 2022 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

cmake_minimum_required(VERSION 3.0)
project(wasm-app)
find_package(vsomeip3)

set (WAMR_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../..)

if (APPLE)
    set (HAVE_FLAG_SEARCH_PATHS_FIRST 0)
    set (CMAKE_C_LINK_FLAGS "")
    set (CMAKE_CXX_LINK_FLAGS "")
endif ()
include_directories(/home/anil/Downloads/vsomeip-master/interface)
link_directories(/home/anil/Downloads/vsomeip-master/build)

set (CMAKE_SYSTEM_PROCESSOR wasm32)

if (NOT DEFINED WASI_SDK_DIR)
    set (WASI_SDK_DIR               "/opt/wasi-sdk")
endif ()

set (CMAKE_C_COMPILER_TARGET        "wasm32-wasi")
set (CMAKE_CXX_COMPILER               "${WASI_SDK_DIR}/bin/clang++")
set (CMAKE_C_FLAGS                  "${CMAKE_C_FLAGS} -O3 -Wno-unused-command-line-argument")

add_executable(file.wasm main.cpp)
target_link_libraries(file.wasm vsomeip3)

I am Using This Cmakelists.txt file. for creating wasm binary. i am include the vsomeip3.so library path in cmakelists.txt and i 
gave vsomeip3 in target_link_libraries. but i am getting  errors like this.

Errors::
wasm-ld: error: cannot open /home/anil/Downloads/vsomeip-master/build: Is a directory
wasm-ld: error: unable to find library -lvsomeip3

**Comment by abrown** [comment]
Not sure how to help here: did you figure this issue out? Feel free to reopen if there's something we can answer here...
