### ISSUE TITLE
Recent macos artifacts are no longer universal binaries

### ISSUE THREAD

**Issue by TerrorJack** [WebAssembly/wasi-sdk#336]
```
$ -bash-5.1$ file wasi-sdk-20.9g00cb3b2e5ffc/bin/clang-16
wasi-sdk-20.9g00cb3b2e5ffc/bin/clang-16: Mach-O 64-bit executable x86_64
```

Looks like to me 9a271da9378b407e7234dcbc26ae60fdd80b6d1a is the culprit. There may be a better way to make sure wasi-sdk builds for aarch64 linux while preserving arm64/x86_64 universal binaries for macos as well, I'll look into it a bit.

**Comment by sbc100** [comment]
It looks like 9a271da should be a no-op on Darwin.   Why/how do you think it made any difference?

**Comment by TerrorJack** [comment]
If you compare sizes of `dist-macos-latest` from https://github.com/WebAssembly/wasi-sdk/actions/runs/4953600854 to https://github.com/WebAssembly/wasi-sdk/actions/runs/5224553231, you'll see it almost halved since that commit, suggesting it is the culprit. For some reason, the artifacts and build logs aren't available for the time being, though I suspect it's a transient GitHub issue and we can look into the artifacts later.

I don't think it's an no-op. We pass `make LLVM_CMAKE_FLAGS=...` and for some reason the append logic in the makefile didn't happen, so it seems.

**Comment by sbc100** [comment]
I see, so its a bug in 9a271da and the `LLVM_CMAKE_FLAGS +=` is not working as expected.    Does one of you (@TerrorJack or @alexcrichton) have time if investigate?   Most likely some kind of GNU Make edge case.

**Comment by alexcrichton** [comment]
Ah sorry I don't have time to investigate this. If it's causing issues feel free to revert the commit.

**Comment by abrown** [comment]
#337 closes this.
