### ISSUE TITLE
About `WASI_SDK_PREFIX` in .cmake

### ISSUE THREAD

**Issue by lum1n0us** [WebAssembly/wasi-sdk#346]
Currently, the command of using *wasi-sdk.cmake* as a toolchain file likes:

```
$ cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/opt/wasi-sdk-20.0/share/cmake/wasi-sdk.cmake -DWASI_SDK_PREFIX=/opt/wasi-sdk-20.0
```

Because of https://github.com/WebAssembly/wasi-sdk/blob/19fb80bcd80ee4381e0b1ba1c480020ca69e7320/wasi-sdk.cmake#L17, it requires to assign two variables in the command line.

My suggestion is shall we either use `${CMAKE_CURRENT_LIST_DIR}/../..` to replace `${WASI_SDK_PREFIX}` or use `CMAKE_CURRENT_LIST_DIR` to assemble `WASI_SDK_PREFIX` and make the command shorter?

**Comment by sbc100** [comment]
Sounds like a good idea!   Feel free to send a PR to that effect.
