### ISSUE TITLE
Package release for Linux ARM64

### ISSUE THREAD

**Issue by JaydenElliott** [WebAssembly/wasi-sdk#347]
I'm building directly on an arm64 linux machine and compiling llvm takes 60+ minutes so would be really helpful to have a release build. 

Is there currently any plan for this? I see a similar, but apple-related issue here #236 as well as some mention of failed arm builds on linux in other tickets. Would be really helpful.

Cheers

**Comment by abrown** [comment]
Well, not all of us have the hardware (and therefore the need) to make this work, but I think it would be a great addition to the project if you want to give this a shot! Like I mentioned in #236, I think this is a matter of modifying the CI workflow, the CI scripts, and (perhaps) the Makefile. Are you interested? We can discuss in more detail on [Zulip](https://bytecodealliance.zulipchat.com/) if you prefer.

**Comment by dicej** [comment]
I'm planning to tackle this soonish, since we're aiming to add Linux (x86_64 and ARM64) support to the .NET NativeAOT-LLVM CI.

**Comment by sparker-arm** [comment]
Would wasi-sdk take advantage of aarch64 github runners now? https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by alexcrichton** [comment]
This is done now from https://github.com/WebAssembly/wasi-sdk/pull/429
