### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by yamt** [WebAssembly/wasi-sdk#348]
can you consider to make a release which includes the following libc bumps?
thank you.

https://github.com/WebAssembly/wasi-sdk/pull/340
https://github.com/WebAssembly/wasi-sdk/pull/344

**Comment by abrown** [comment]
Sure, I can start looking into making a new release. Some things to think about:
 - should we wait for LLVM 17 to be [released ](https://github.com/llvm/llvm-project/releases/) in case anyone wants something from that?
 - should we wait for https://github.com/WebAssembly/wasi-libc/pull/434 and https://github.com/WebAssembly/wasi-libc/pull/435?

**Comment by yamt** [comment]
> Sure, I can start looking into making a new release. Some things to think about:
> 
>     * should we wait for LLVM 17 to be [released ](https://github.com/llvm/llvm-project/releases/) in case anyone wants something from that?
> 
>     * should we wait for [Rename wasm32-wasi-threads target to wasm32-wasi-preview1-threads wasi-libc#434](https://github.com/WebAssembly/wasi-libc/pull/434) and [Update thread id validation returned by `__wasi_thread_spawn` wasi-libc#435](https://github.com/WebAssembly/wasi-libc/pull/435)?

i don't think we should wait for any of the above.
i guess it's a bit more user-friendly to avoid tying bug fixes and major changes like llvm bump together.

**Comment by glebpom** [comment]
LLVM 17 is released now

**Comment by yamt** [comment]
sorry, is making a release that much work?

**Comment by abrown** [comment]
More than I would like it to! The CI [scripts](https://github.com/WebAssembly/wasi-sdk/tree/main/ci) help but it's still a bit manual... and things can go wrong. That's why I haven't set up a "one click to release" CI job.

**Comment by abrown** [comment]
Also, I'm hearing that @dicej might want to get https://github.com/WebAssembly/wasi-libc/pull/429 in to this release?

**Comment by dicej** [comment]
Indeed I do.  Just need someone with authority to approve and merge it.  Happy to help with the release process, too.

**Comment by yamt** [comment]
just https://github.com/WebAssembly/wasi-libc/pull/429?
or do you mean to finish https://github.com/WebAssembly/wasi-sdk/pull/338 as well?

**Comment by dicej** [comment]
> just [WebAssembly/wasi-libc#429](https://github.com/WebAssembly/wasi-libc/pull/429)? or do you mean to finish #338 as well?

Both.  I've been waiting for the wasi-libc PR to be merged so I can update the submodule in wasi-sdk.

**Comment by dicej** [comment]
Looks like that's happened, so I'll update #338 today.

**Comment by rockwotj** [comment]
Personally, I'd love a release with clang 17, but not sure how much more #338 needs

**Comment by dicej** [comment]
I think #338 is ready to merge now.  BTW, LLVM 17.0.6 is scheduled to be released two days from now, so we might consider waiting for that rather than the release/17.x snapshot I pointed to in #338.

**Comment by turbolent** [comment]
Would it be possible to release a bugfix release with the threading bugfixes in libc?

**Comment by yamt** [comment]
> I think #338 is ready to merge now. BTW, LLVM 17.0.6 is scheduled to be released two days from now, so we might consider waiting for that rather than the release/17.x snapshot I pointed to in #338.

i think it makes sense to wait for the release.

**Comment by yamt** [comment]
> Would it be possible to release a bugfix release with the threading bugfixes in libc?

those fixes which have already been merged in wasi-libc will be in the next release i guess.

or, do you mean to have a separate bugfix-only release?
@abrown prefers to have more things in a release to save releng efforts.

**Comment by loganek** [comment]
Is there a plan to enable exceptions support in the upcoming release?

**Comment by dicej** [comment]
> > I think #338 is ready to merge now. BTW, LLVM 17.0.6 is scheduled to be released two days from now, so we might consider waiting for that rather than the release/17.x snapshot I pointed to in #338.
> 
> i think it makes sense to wait for the release.

I've updated #338 to use LLVM 17.0.6.

**Comment by abrown** [comment]
Ok, as I understand it, once #338 gets merged then we can release v21?

**Comment by yamt** [comment]
> Is there a plan to enable exceptions support in the upcoming release?

i don't think so.

**Comment by yamt** [comment]
> > > I think #338 is ready to merge now. BTW, LLVM 17.0.6 is scheduled to be released two days from now, so we might consider waiting for that rather than the release/17.x snapshot I pointed to in #338.
> > 
> > 
> > i think it makes sense to wait for the release.
> 
> I've updated #338 to use LLVM 17.0.6.

thank you.

**Comment by abrown** [comment]
Ok, I'm closing this now that [wasi-sdk-21](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-21) has been published as a pre-release. We can promote it to a full release whenever; I just wanted to give people a chance to test things out.
