### ISSUE TITLE
Missing debug information 

### ISSUE THREAD

**Issue by bbbshaw** [WebAssembly/wasi-sdk#350]
Hi,

I use wasi-sdk to compile a simple c program and use objdump to print the .wasm file information. I found that when using -O0 as the optimization level, the debug information can be seen. However, when using -O2  as the optimization level, the debug information would be lost. 

Here is the simple c program:
```c
#include <stdio.h>

int main(void){
    printf("helloworld");
}
``` 

I use the following command to compile:

`/wasi-sdk-20.0/bin/clang --sysroot /wasi-sdk-20.0/share/wasi-sysroot helloworld.c -g -O2  -o hello.wasm`

I use the following command to dump the .wasm file:

`llvm-objdump -S -l hello.wasm`

The result doesn't show any debug information.

**Comment by abrown** [comment]
Is it possible you're running into https://github.com/llvm/llvm-project/issues/55781?

**Comment by bbbshaw** [comment]
No, I have tried both /wasi-sdk-20.0/bin/llvm-objdump and llvm/llvm-objdump. The results are the same.

**Comment by bbbshaw** [comment]
> Is it possible you're running into [llvm/llvm-project#55781](https://github.com/llvm/llvm-project/issues/55781)?

No, I have tried both /wasi-sdk-20.0/bin/llvm-objdump and llvm/llvm-objdump. The results are the same.

**Comment by sbc100** [comment]
Do you have `wasm-opt` in your path?

**Comment by bbbshaw** [comment]
> Is it possible you're running into [llvm/llvm-project#55781](https://github.com/llvm/llvm-project/issues/55781)?

Thanks for sharing this issue. I believe it's the reason why debug information is missing.

**Comment by abrown** [comment]
We really need to fix that issue. In the meantime, how do you feel about closing this one to avoid duplicates?

**Comment by bbbshaw** [comment]
> We really need to fix that issue. In the meantime, how do you feel about closing this one to avoid duplicates?

Sure, I appreciate your help and will close this issue.
