### ISSUE TITLE
How to tell what version of the WASI-SDK is installed?

### ISSUE THREAD

**Issue by brettcannon** [WebAssembly/wasi-sdk#372]
E.g., is there a text file somewhere I can have users look at to tell me what they tried using? (Context: https://github.com/python/cpython/issues/113516).

**Comment by abrown** [comment]
Reading through the issue, I see what you mean. Usually it's apparent if the user shows the full path to Clang, e.g., `/opt/wasi-sdk-20.0/bin/clang`. But it seems reasonable to add a version file somewhere for this kind of situation.

**Comment by sbc100** [comment]
Some kind of version.h header might be good idea
