### ISSUE TITLE
libcxx's `<fstream>` no longer works as of `wasi-sdk` 21

### ISSUE THREAD

**Issue by dicej** [WebAssembly/wasi-sdk#373]
As of LLVM 17, which includes https://reviews.llvm.org/D152168, libcxx has combined the old `_LIBCPP_HAS_NO_FILESYSTEM_LIBRARY` and `_LIBCPP_HAS_NO_FSTREAM` preprocessor symbols into a single `_LIBCPP_HAS_NO_FILESYSTEM` symbol, which means there's no longer any way to enable `<fstream>` without enabling `<filesystem>`.  Consequently, `wasi-sdk` 21 no longer supports e.g. `std::ifstream` etc.

The solution may involve setting `-DLIBCXX_ENABLE_FILESYSTEM:BOOL=ON` and then fixing the breakage.  I just tried that and hit `fatal error: 'sys/statvfs.h' file not found`.  I'm going to try creating that file and adding stubs to it to see how far I get.  Meanwhile, I'm open to alternative approaches.

**Comment by sbc100** [comment]
Probably best to modify libc++ upstream to not depend on `statvfs.h` when building for wasi.

**Comment by dicej** [comment]
@sbc100 it's ugly, but it works: https://github.com/dicej/llvm-project/commit/4fe474048f5ddd1efbb938e38fa78e40ddf89f46

Note that it wasn't just `statvfs`, but also `realpath`, `chmod`, etc.

Does that seem appropriate to submit as an upstream PR?

**Comment by sunfishcode** [comment]
I just had an idea: I expect WASI will be adding `chmod` and `realpath` in the future; `statvfs` is trickier, but perhaps WASI could provide at least some of the fields in the future. So, what if for now, we add stubs to wasi-libc for `chmod`, `realpath`, and `statvfs`, which all fail with `ENOSYS`? That should be enough to fix the libcxx build errors, and then we can fill in the implementations as WASI adds the underlying support.

Does that sound reasonable?

**Comment by dicej** [comment]
This is fixed by https://github.com/WebAssembly/wasi-libc/pull/463 -- just need to update the `wasi-libc` submodule in this repo to pull it in.
