### ISSUE TITLE
Status of thread support

### ISSUE THREAD

**Issue by sparker-arm** [WebAssembly/wasi-sdk#379]
(Building on AArch64 Ubuntu)

When checking out wasi-sdk-21, wasm32-wasi-threads support is built by default, but this is not the case on main.

wasi-libc has documentation on how to build support thread, is there something similar for the whole of wasi-sdk?

Thanks!

**Comment by abrown** [comment]
Can you explain in more detail what commands you are running and what you expected to happen (e.g., what files you expected to see but are missing)?

**Comment by sparker-arm** [comment]
I've just gone through the steps to reproduce my problem.... and it turns out there isn't one. I don't know what I did wrong before - sorry for the noise!
