### ISSUE TITLE
What's the official name of the project?

### ISSUE THREAD

**Issue by brettcannon** [WebAssembly/wasi-sdk#383]
Is it "WASI SDK" or "WASI-SDK" (i.e. w/ or w/o a hyphen)? The usage is inconsistent in the README.

**Comment by sunfishcode** [comment]
Let's go with "WASI SDK", with no hyphen, because that's the one that's at the top of the README.md in H1.

The repo and packages and paths can continue to use wasi-sdk.

**Comment by brettcannon** [comment]
https://github.com/WebAssembly/wasi-sdk/pull/384 should hopefully make the naming consistent.
