### ISSUE TITLE
Older command line arguments failing in wasm-ld

### ISSUE THREAD

**Issue by kushaldas** [WebAssembly/wasi-sdk#385]
While building CPython with `wasi-sdk-21` I got the following error.

```
/opt/wasi-sdk/bin/wasm-ld   -z stack-size=524288 -Wl,--stack-first -Wl,--initial-memory=10485760   Modules/_testimportmultiple.o   -o Modules/_testimportmultiple.cpython-313d-wasm32-wasi.so
wasm-ld: error: unknown argument: -Wl,--stack-first
wasm-ld: error: unknown argument: -Wl,--initial-memory=10485760
make: *** [Makefile:3183: Modules/_testimportmultiple.cpython-313d-wasm32-wasi.so] Error 1
```

Can you please tell me what are the new/expected arguments to `wasm-ld` for this?

**Comment by sbc100** [comment]
If you are invoking the linker directly you don't prefix the linker args with `-Wl,`.  That prefix is what the compiler driver (`clang`) uses to distinguish linker argument.

**Comment by brettcannon** [comment]
> If you are invoking the linker directly you don't prefix the linker args with `-Wl,`. That prefix is what the compiler driver (`clang`) uses to distinguish linker argument.

This [comes from CPython's `configure.ac`](https://github.com/python/cpython/blob/2f0778675ad0eaf346924ef6a2f60529b92ffcfa/configure.ac#L2240) and has worked until now (e.g. WASI SDK 20 is fine with this). So we're trying to figure out who/what changed.

**Comment by brettcannon** [comment]
I found the issue on our side. We had not seen it before because `dlopen()` never existed before. 😅

**Comment by kushaldas** [comment]
Closing the issue.
