### ISSUE TITLE
Windows released binaries and/or build instructions

### ISSUE THREAD

**Issue by vvuk** [WebAssembly/wasi-sdk#39]
I'm unable to find instructions on building a version of the SDK, so that I can do a windows build.  Alternatively, it would be quite nice to have windows released builds available.

**Comment by qis** [comment]
Theoretically, you can build `llvm` and `clang` on windows:

```cmd
cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel ^
  -DCMAKE_INSTALL_PREFIX="C:/LLVM" ^
  -DDEFAULT_SYSROOT="C:/LLVM/sysroot" ^
  -DLLVM_ENABLE_PROJECTS="clang;lld" ^
  -DLLVM_TARGETS_TO_BUILD="WebAssembly" ^
  -DLLVM_DEFAULT_TARGET_TRIPLE=wasm32-wasi ^
  -DLLVM_ENABLE_ASSERTIONS=OFF ^
  -DLLVM_ENABLE_WARNINGS=OFF ^
  -DLLVM_ENABLE_PEDANTIC=OFF ^
  -DLLVM_ENABLE_DIA_SDK=OFF ^
  -DLLVM_INCLUDE_EXAMPLES=OFF ^
  -DLLVM_INCLUDE_TESTS=OFF ^
  -DLLVM_INCLUDE_DOCS=OFF ^
  -DCLANG_DEFAULT_STD_C="c99" ^
  -DCLANG_DEFAULT_STD_CXX="cxx17" ^
  -DCLANG_DEFAULT_CXX_STDLIB="libc++" ^
  -DCLANG_DEFAULT_RTLIB="compiler-rt" ^
  -DCLANG_DEFAULT_LINKER="wasm-ld" ^
  -B llvm-build llvm/llvm
cmake --build llvm-build --target install
```

then compile `wasi-sdk` in WSL (or in a Linux VM) and copy the `share/wasi-sysroot` and `lib/clang/8.0.0/lib` directories to the Windows filesystem.

**Comment by tschneidereit** [comment]
@vvuk, I started setting up [CI for wasi-sdk](https://github.com/CraneStation/wasi-sdk/commit/3dad95d1f3360430de0233ad0883c9481487fd74), but got stuck on Windows build system issues. These are probably fairly easy to resolve for someone with any knowledge of Windows at all :)

I'll set up automated releases for the other platforms in the next couple of weeks, which we should be able to extend to Windows builds quite easily once those work.

**Comment by vvuk** [comment]
Boy, time flies :)  I see that the repo moved to GitHub Actions recently.  I'm happy to try to get things working on Windows.  I think if I clone the repo I should be able to edit actions and such?

**Comment by sbc100** [comment]
Yup, actions should work fine in your fork.

Sadly it looks like we github are ramping up billing for action minutes so we might need to figure out our response: https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions.

**Comment by vvuk** [comment]
@sbc100 I just put a PR up, but can't ask for review on it; please take a look when you get a chance.  The windows build action seems to take ~2.5hrs.
