### ISSUE TITLE
How to compile C into Wasm with wasi_preview2?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WebAssembly/wasi-sdk#405]
How to compile C into Wasm with wasi_preview2?

Now using command `./wasi-sdk-16.0/bin/clang --target=wasm32-unkown-wasi --sysroot=./wasi-sdk-16.0/share/wasi-sysroot {file1} -o {file2}"` could only get Wasm file with wasi_preview1.

**Comment by abrown** [comment]
That is currently being worked on so you may not have an easy-to-use binary just yet (cc: @dicej, @sunfishcode). If you really, really want to try out a preview 2 compilation and don't mind some unfinished bits, try building the latest [wasi-libc] and use the `wasm32-wasip2` target. You'll have to pass your custom-built wasi-libc sysroot in to `--sysroot`. (And I would recommend using a much more recent version of wasi-sdk).

[wasi-sdk-21]: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-21
[wasi-libc]: https://github.com/WebAssembly/wasi-libc

**Comment by Userzxcvbvnm** [comment]
Thanks for your reply !
