### ISSUE TITLE
Next release of wasi-sdk-22

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wasi-sdk#408]
I wanted to open this up and see if anyone had any objections to publishing a v22 release for wasi-sdk. I'm happy to drive using the instructions @abrown [has added](https://github.com/WebAssembly/wasi-sdk/blob/main/RELEASING.md), but wanted to make sure beforehand there were no objections.

**Comment by sunfishcode** [comment]
Sounds good to me.

**Comment by alexcrichton** [comment]
I've [created a tag](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-22) which has [kicked off a build](https://github.com/WebAssembly/wasi-sdk/actions/runs/8663908594)

**Comment by alexcrichton** [comment]
The release artifacts are not built correctly so I've deleted the tag.

One issue is https://github.com/WebAssembly/wasi-sdk/pull/409 where `./version.py` was putting a git hash in the version number when it shouldn't. Another issue is CI built artifacts with a version number of 21.21... which should have been 22.0... and I am trying to figure out why and am being pretty unsuccessful.

**Comment by alexcrichton** [comment]
I believe the second issue is https://github.com/WebAssembly/wasi-sdk/pull/410, I'll retry the release once those are merged

**Comment by abrown** [comment]
> One issue is #409 where `./version.py` was putting a git hash in the version number when it shouldn't. Another issue is CI built artifacts with a version number of 21.21... which should have been 22.0... and I am trying to figure out why and am being pretty unsuccessful.

Did my comment in #409 clear things up?

**Comment by alexcrichton** [comment]
Yeah sounds good! I'll try a re-tag now and see how it goes

**Comment by alexcrichton** [comment]
Ok https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-22 was produced just now and things look better. If other folks want to give some eyes on that I can hit the publish button later today or tomorrow.

**Comment by alexcrichton** [comment]
Ok I've hit publish.

**Comment by abrown** [comment]
I opened https://github.com/WebAssembly/wasi-sdk/pull/414 to see if I could figure out where the extra `m` suffix came from.
