### ISSUE TITLE
New artifacts in wasi-sdk-22 release

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wasi-sdk#420]
I just re-installed `wasi-sdk-22` again (the `-linux` version) and noticed a few new files:
- `.crates2.json`
```
{"installs":{"wasm-component-ld 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)":{"version_req":"=0.1.5","bins":["wasm-component-ld"],"features":[],"all_features":false,"no_default_features":false,"profile":"release","target":"x86_64-unknown-linux-gnu","rustc":"rustc 1.77.2 (25ef9e3d8 2024-04-09)\nbinary: rustc\ncommit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\ncommit-date: 2024-04-09\nhost: x86_64-unknown-linux-gnu\nrelease: 1.77.2\nLLVM version: 17.0.6\n"}}}
```

- `.crates.toml`
```
[v1]
"wasm-component-ld 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-component-ld"]
```

I suspect these are coming from #416; @alexcrichton, do we need/want these files?

**Comment by alexcrichton** [comment]
Oop no we should delete those files and or use a different `--root` and copy things over manually

**Comment by bjorn3** [comment]
You can use `cargo install --no-track` to avoid creating these files in the first place.

**Comment by abrown** [comment]
Nope, looks like #432 did not in fact fix the issue, or perhaps there is something else going on here:

```console
$ ll /opt/wasi-sdk/latest/
bin/           .crates2.json  .crates.toml   lib/           share/         VERSION
```

**Comment by alexcrichton** [comment]
I believe this is fixed in https://github.com/WebAssembly/wasi-sdk/pull/429, so closing.
