### ISSUE TITLE
Turn exceptions into unreachable

### ISSUE THREAD

**Issue by orsinium** [WebAssembly/wasi-sdk#428]
I want to compile with wasi-sdk a C++17 project that uses exceptions. As the wasi-sdk readme says, the proper exceptions are not supported and it refers to the [exception handling proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/exception-handling/Exceptions.md). However, the project I'm interested in doesn't use exceptions for control flow, so it should be safe to turn all exceptions into `unreachable`.

Question: is there a way to instruct wasi-sdk to compile exceptions as `unreachable`?

Caused by https://github.com/pocketpy/pocketpy/issues/275

**Comment by agoode** [comment]
The readme mentions `-fno-exceptions` which I think will have the effect of turning exceptions into `abort()` which is implemented as `unreachable`.

**Comment by orsinium** [comment]
Will it? This is what I currently use but I wasn't 100% sure that it won't just remove exceptions. `clang --help` isn't very helpful:

```
-fno-exceptions         Disable support for exception handling
```

**Comment by agoode** [comment]
It looks like yes: https://stackoverflow.com/questions/7249378/disabling-c-exceptions-how-can-i-make-any-std-throw-immediately-terminate

`-fno-exceptions` is one of the GCC-compatibility flags that clang supports. So the GCC documentation may (or may not) be helpful: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_exceptions.html

**Comment by orsinium** [comment]
Thank you!
