### ISSUE TITLE
`VERSION` file missing from WASI SDK 24

### ISSUE THREAD

**Issue by SingleAccretion** [WebAssembly/wasi-sdk#471]
I downloaded `wasi-sdk-24.0-x86_64-windows.tar.gz` from the 24's release [artifacts](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-24), and the `VERSION` file that was there in 22 is missing, which does not look right.

**Comment by abrown** [comment]
Some initial findings:
 - the new CMake build (from #429) should be trying to build the `VERSION` file ([here](https://github.com/WebAssembly/wasi-sdk/blob/d2bea01edcc46f731156a817f710cdd9fc9c1c19/cmake/wasi-sdk-sysroot.cmake#L328-L337))
 - it isn't, even for the released Linux artifacts (this is not just a Windows issue)
 - when I build this locally using `ci/build.sh`, the `VERSION` file does actually appear in `build/install`
 - but `VERSION` does not appear in `build/dist` so I think CI is not picking it with the `upload-artifact` artifact action (confirmed: it is not present in the downloaded `dist-x86_64-linux.zip` from GitHub actions)
 - once we do fix the copying to `build/dist`, do we need to update `ci/merge-artifacts.sh` to make sure it gets merged into the final `*.tar` file? (Alternately, we could stuff `VERSION` into one of the component `*.tar`s).

**Comment by alexcrichton** [comment]
Ah yes my mistake! Can confirm that `VERSION` is only in the install and not in the tarballs. I do believe that `merge-artifacts.sh` will need to be updated to copy it from one tarball to another. I can work on this when I get back next week if no one else solves it in the meantime.
