### ISSUE TITLE
Local rebuild fails on non-empty `dist` directory

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wasi-sdk#486]
To avoid the issues in #485, I can manually set ` -DWASI_SDK_INCLUDE_TESTS=OFF` in `ci/build.sh` and disable building the tests, but if a previous build has failed, the build will fail because a `dist` directory is not empty:

```console
$ WASI_SDK_CI_SKIP_TESTS=1 ci/build.sh
...
[2/2] cd /home/abrown/Code/wasi-sdk/build/toolchain/dist && cp -R /home/abrown/Code/wasi-sdk/build/toolchain/install
wasi-toolchain-24.6g754aec3d6f58+m-x86_64-linux && /usr/bin/cmake -E tar cfz
/home/abrown/Code/wasi-sdk/build/toolchain/dist/wasi-toolchain-24.6g754aec3d6f58+m-x86_64-linux.tar.gz wasi-toolchain-24.6g754aec3d6f58+m-x86_64-linux &&
/usr/bin/cmake -E rm -rf wasi-toolchain-24.6g754aec3d6f58+m-x86_64-linux
+ mv /home/abrown/Code/wasi-sdk/build/toolchain/dist /home/abrown/Code/wasi-sdk/build/dist
mv: cannot overwrite '/home/abrown/Code/wasi-sdk/build/dist/dist': Directory not empty
```

Could it be that CMake needs some more instructions here to know these artifacts are already built?

**Comment by alexcrichton** [comment]
Oh the `./ci/build.sh` script isn't necessarily written to be run and rerun locally. For that it probably needs more than a few updates (in addition to handling this `dist` directory differently). For local development I've been relying on running `cmake` and `ninja` manually.
