### ISSUE TITLE
string pointer invalidation after large resize allocation

### ISSUE THREAD

**Issue by sentriz** [WebAssembly/wasi-sdk#500]
hi there, I'm trying to reproduce a bug I see when compiling TagLib and their [String](https://github.com/taglib/taglib/blob/master/taglib/toolkit/tstring.cpp) class. when it's defined as a [static global](https://github.com/taglib/taglib/blob/225c73e1816c3200c67703557972586e287fa665/taglib/mpeg/id3v2/id3v2frame.cpp#L81) 

when accessing it from a WASM exported function, the string appears empty (stream of null bytes)

however, this isn't the case when calling from main()

```cpp
const TagLib::String instrumentPrefix("PERFORMER:");

__attribute__((export_name("print_instrument_prefix"))) void print_instrument_prefix() {
    std::cout << instrumentPrefix; // it's empty
}

int main() {
    std::cout << instrumentPrefix; // it works
    return 0;
};
```

---

to try narrow the issue down, I tried to copy what their String class does as best I can. I'm not a C++ dev so I'm sure it could be better. but it certainly seems to exhibit the same behaviour

it goes like this

```cpp
#include <iostream>

const auto EXAMPLE = std::make_shared<std::string>("hello");

std::string copy(std::string &input) {
  std::string result;
  result.resize(input.size() * 8);

  const char *data_start = input.data();
  const char *data_end = data_start + input.size();

  size_t pos = 0;
  while (data_start != data_end) {
    result[pos] = static_cast<char>(*data_start++);
    pos++;
  }

  result.resize(pos);
  return result;
}

// not working
// output:
//   b: 
//   b size: 0 
__attribute__((export_name("do_debug"))) void do_debug() {
  auto s = copy(*EXAMPLE);
  std::cout << "b: " << s << std::endl;
  std::cout << "b size: " << s.size() << std::endl;
}

// working
// output:
//   b: hello
//   b size: 5
int main() {
  auto s = copy(*EXAMPLE);
  std::cout << "b: " << s << std::endl;
  std::cout << "b size: " << s.size() << std::endl;
  return 0;
};
``` 

it looks a bit weird but it's based on their string which is internally represented as a std::wstring, which gets copied to std::string with some buffer. for this example I used std::string and made the buffer larger anyway

as you can see, it works from main(), and not do_debug()

to make things more strange, not resizing fixes it

works:

```diff
   std::string result;
-  result.resize(input.size() * 8);
+  result.resize(input.size());
```

any ideas what's going on here? if it helps, I'm using wasi-sdk like so:

`clang++ -target wasm32-wasi --sysroot /opt/wasi-sdk/share/wasi-sysroot main.cpp -Wl,--allow-undefined -o main.wasm`

**thank you!**

---

PS here is one more example which also reproduces the behaviour. this time we hack a `wstring` -> `string`, where we do need the resize

```cpp
// is now a wstring
const auto EXAMPLE = std::make_shared<std::wstring>(L"hello");

std::string convertString(std::wstring &input) {
  std::string result;
  result.resize(input.size() * 4);

  size_t pos = 0;
  const wchar_t *data_start = input.data();
  const wchar_t *data_end = data_start + input.size();

  while (data_start != data_end) {
    result[pos] = static_cast<char>(*data_start++);
    pos++;
  }

  result.resize(pos);
  return result;
}

// not working
// output:
//   b: 
//   b size: 0
__attribute__((export_name("do_debug"))) void do_debug() {
  auto s = convertString(*EXAMPLE);
  std::cout << "b: " << s << std::endl;
  std::cout << "b size: " << s.size() << std::endl;
}
```

to fix this one, we can just move the resize: 

```diff
-  std::string result;
-  result.resize(input.size() * 4);

   size_t pos = 0;
   const wchar_t *data_start = input.data();
   const wchar_t *data_end = data_start + input.size();

+  std::string result;
+  result.resize(input.size() * 4);
```

**Comment by sunfishcode** [comment]
Do I understand correctly that you're calling the `print_instrument_prefix` export, or the `do_debug` export, before calling the `_start` export which calls `main`? If so, then that's likely the source of the problem; C++ global constructors are called when `_start` is called, so if you're calling into an export before that, static variables like `EXAMPLE` aren't constructed yet.

If that's the case, could you say more about the environment in which you're calling these exports? Depending on what you're doing, there may be ways to fix this.

**Comment by sentriz** [comment]
@sunfishcode I'm using Go and [wazero](https://github.com/tetratelabs/wazero) as the host

it does indeed call _start, and later the exported function. all in the same Module

I created a reproduction repo here: https://github.com/sentriz/taglib-string-wasm-repro

as you can see when calling from main it works, but later fails in the exported func 

![image](https://github.com/user-attachments/assets/0286f6b3-dbda-4553-ac57-ae062602a2d9)

**Comment by TerrorJack** [comment]
Shouldn't you be linking with `-mexec-model=reactor` and calling `_initialize` instead? Because `_start` will also call `__wasm_call_dtors` that call all C++ destructors, which I assume will make any C++ function invocation undefined behavior after that point?

**Comment by sentriz** [comment]
@TerrorJack that did it! thank you so much. been really pulling my hair out on this. and I didn't know about __wasm_call_dtors

thanks!!
