### ISSUE TITLE
Can we have clang find the sysroot using a relative path?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wasi-sdk#58]
Today we configure llvm with `-DDEFAULT_SYSROOT=/opt/wasi-sdk/share/wasi-sysroot` which means the resulting toolchain will work as expected only when installed in `/opt/wasi-sdk`.

Installing it anywhere else (e.g. just untaring it somewhere) will mean that one needs to pass the `--sysroot=..` flag to each compiler invocation. 

Perhaps there is some way we can find the default sysroot relative the compiler binary?

Followup from #57

**Comment by aseering** [comment]
If you can't easily make this change, would you consider posting somewhere obvious in the docs that passing `--sysroot=..` is necessary and/or that extracting build tarballs to `/opt/wasi-sdk` is recommended?  I extracted to `/opt/wasi-sdk-8.0` (the default directory name in that version's tarball) and only stumbled across this ticket when I went to file a bug about the build not working :-)

**Comment by sbc100** [comment]
Proposed fix on the llvm side: https://reviews.llvm.org/D76653
