### ISSUE TITLE
Release version 9 with snapshot1 version libc.

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wasi-sdk#86]
Are we ready to do this?

**Comment by pchickey** [comment]
I'd like to attempt to use the artifacts built on Actions for the release, so lets merge #83 and then go for it

**Comment by pchickey** [comment]
Actually, lets try to resolve https://github.com/CraneStation/wasi-libc/issues/146 first

**Comment by sunfishcode** [comment]
https://github.com/CraneStation/wasi-libc/pull/148 has a fix.

**Comment by pchickey** [comment]
Hmm, this got lost in all of our other tasks, I think. Is there anything blocking cutting release 9 right now? If not, I'll take care of doing the release.

**Comment by pchickey** [comment]
Heres the outstanding PRs:
[ ] #89 is approved but based on an out-of-date wasi-libc. needs rebase.
[ ] #107 appears ready, awaiting sign-off by @sunfishcode 
[ ] #109 appears ready, awaiting sign-off by @sunfishcode 
[ ] #113 I just opened to bump to the very latest wasi-libc, which only has a readme change, so no effect to this repo

**Comment by pchickey** [comment]
Additionally, https://github.com/WebAssembly/wasi-libc/pull/188 fixes a regression from the last release (utime.h was present, this breaks at least one test in lucet) so lets get that one in if we reasonably can

**Comment by sunfishcode** [comment]
#89 should be coordinated with https://github.com/WebAssembly/wasi-libc/pull/150, which isn't quite ready to go yet. It's fine to leave it out for this release.

The rest of the PRs are now merged.

**Comment by pchickey** [comment]
Ok! Lets leave it out of the release. I'm about to call it a week at work, hopefully we can figure out what Mac CI stuff is going wrong and cut the release on Monday.

**Comment by pchickey** [comment]
I tagged the release and uploaded built artifacts for linux and mac: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-9

I'll write up release notes tomorrow
