### ISSUE TITLE
wasi-sdk 8.0 libstdc++ required version is too high

### ISSUE THREAD

**Issue by acfoltzer** [WebAssembly/wasi-sdk#98]
On an Ubuntu Xenial system, I see:
```
/opt/wasi-sdk/bin/clang: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22\' not found (required by /opt/wasi-sdk/bin/clang)
```
This hasn't been an issue with past releases, and seems to be new since basing the Dockerfile on Debian stretch rather than Xenial. Could we consider switching back to Xenial, or an older version of Debian that would pull in a compatible `libstdc++`?

**Comment by sbc100** [comment]
Sure, we can try that.  I hadn't realized when I submitted #65 and stretch was more recent than xenial.  I guess we could try going back to jessie which pre-dates both of them.

**Comment by acfoltzer** [comment]
It's odd because Xenial is based on stretch (according to `/etc/debian_version` at least), but maybe stretch has gotten newer C++ libraries over the years?
